// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: usersvc.proto

package usersvcclient

import (
	"context"

	"usersvc/usersvc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp              = usersvc.CommonResp
	GetDispatchConfigReq    = usersvc.GetDispatchConfigReq
	GetDispatchConfigResp   = usersvc.GetDispatchConfigResp
	GetMessagesReq          = usersvc.GetMessagesReq
	GetMessagesResp         = usersvc.GetMessagesResp
	GetProfileReq           = usersvc.GetProfileReq
	GetProfileResp          = usersvc.GetProfileResp
	GetQualificationReq     = usersvc.GetQualificationReq
	GetQualificationResp    = usersvc.GetQualificationResp
	GetVehicleReq           = usersvc.GetVehicleReq
	GetVehicleResp          = usersvc.GetVehicleResp
	GetWalletReq            = usersvc.GetWalletReq
	GetWalletResp           = usersvc.GetWalletResp
	HeartbeatReq            = usersvc.HeartbeatReq
	LoginReq                = usersvc.LoginReq
	LoginResp               = usersvc.LoginResp
	MessageItem             = usersvc.MessageItem
	SetOnlineStatusReq      = usersvc.SetOnlineStatusReq
	SubmitQualificationReq  = usersvc.SubmitQualificationReq
	SubmitVehicleReq        = usersvc.SubmitVehicleReq
	UpdateBankCardReq       = usersvc.UpdateBankCardReq
	UpdateDispatchConfigReq = usersvc.UpdateDispatchConfigReq
	WithdrawReq             = usersvc.WithdrawReq

	Usersvc interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileResp, error)
		SubmitQualification(ctx context.Context, in *SubmitQualificationReq, opts ...grpc.CallOption) (*CommonResp, error)
		GetQualification(ctx context.Context, in *GetQualificationReq, opts ...grpc.CallOption) (*GetQualificationResp, error)
		SubmitVehicle(ctx context.Context, in *SubmitVehicleReq, opts ...grpc.CallOption) (*CommonResp, error)
		GetVehicle(ctx context.Context, in *GetVehicleReq, opts ...grpc.CallOption) (*GetVehicleResp, error)
		SetOnlineStatus(ctx context.Context, in *SetOnlineStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
		Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*CommonResp, error)
		UpdateDispatchConfig(ctx context.Context, in *UpdateDispatchConfigReq, opts ...grpc.CallOption) (*CommonResp, error)
		GetDispatchConfig(ctx context.Context, in *GetDispatchConfigReq, opts ...grpc.CallOption) (*GetDispatchConfigResp, error)
		GetWallet(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWalletResp, error)
		Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*CommonResp, error)
		GetMessages(ctx context.Context, in *GetMessagesReq, opts ...grpc.CallOption) (*GetMessagesResp, error)
		UpdateBankCard(ctx context.Context, in *UpdateBankCardReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultUsersvc struct {
		cli zrpc.Client
	}
)

func NewUsersvc(cli zrpc.Client) Usersvc {
	return &defaultUsersvc{
		cli: cli,
	}
}

func (m *defaultUsersvc) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUsersvc) GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

func (m *defaultUsersvc) SubmitQualification(ctx context.Context, in *SubmitQualificationReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.SubmitQualification(ctx, in, opts...)
}

func (m *defaultUsersvc) GetQualification(ctx context.Context, in *GetQualificationReq, opts ...grpc.CallOption) (*GetQualificationResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.GetQualification(ctx, in, opts...)
}

func (m *defaultUsersvc) SubmitVehicle(ctx context.Context, in *SubmitVehicleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.SubmitVehicle(ctx, in, opts...)
}

func (m *defaultUsersvc) GetVehicle(ctx context.Context, in *GetVehicleReq, opts ...grpc.CallOption) (*GetVehicleResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.GetVehicle(ctx, in, opts...)
}

func (m *defaultUsersvc) SetOnlineStatus(ctx context.Context, in *SetOnlineStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.SetOnlineStatus(ctx, in, opts...)
}

func (m *defaultUsersvc) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.Heartbeat(ctx, in, opts...)
}

func (m *defaultUsersvc) UpdateDispatchConfig(ctx context.Context, in *UpdateDispatchConfigReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.UpdateDispatchConfig(ctx, in, opts...)
}

func (m *defaultUsersvc) GetDispatchConfig(ctx context.Context, in *GetDispatchConfigReq, opts ...grpc.CallOption) (*GetDispatchConfigResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.GetDispatchConfig(ctx, in, opts...)
}

func (m *defaultUsersvc) GetWallet(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWalletResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.GetWallet(ctx, in, opts...)
}

func (m *defaultUsersvc) Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.Withdraw(ctx, in, opts...)
}

func (m *defaultUsersvc) GetMessages(ctx context.Context, in *GetMessagesReq, opts ...grpc.CallOption) (*GetMessagesResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

func (m *defaultUsersvc) UpdateBankCard(ctx context.Context, in *UpdateBankCardReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := usersvc.NewUsersvcClient(m.cli.Conn())
	return client.UpdateBankCard(ctx, in, opts...)
}
