// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"XiaoLong-Ridy/rpc/adminsvc/adminsvc"
	"XiaoLong-Ridy/rpc/adminsvc/internal/logic/adminservice"
	"XiaoLong-Ridy/rpc/adminsvc/internal/svc"
)

type AdminServiceServer struct {
	svcCtx *svc.ServiceContext
	adminsvc.UnimplementedAdminServiceServer
}

func NewAdminServiceServer(svcCtx *svc.ServiceContext) *AdminServiceServer {
	return &AdminServiceServer{
		svcCtx: svcCtx,
	}
}

// 管理员注册。
func (s *AdminServiceServer) Register(ctx context.Context, in *adminsvc.RegisterRequest) (*adminsvc.AuthResponse, error) {
	l := adminservicelogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 管理员登录。
func (s *AdminServiceServer) Login(ctx context.Context, in *adminsvc.LoginRequest) (*adminsvc.AuthResponse, error) {
	l := adminservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 管理员退出登录。
func (s *AdminServiceServer) Logout(ctx context.Context, in *adminsvc.LogoutRequest) (*adminsvc.CommonResponse, error) {
	l := adminservicelogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// 查询当前管理员信息。
func (s *AdminServiceServer) Me(ctx context.Context, in *adminsvc.MeRequest) (*adminsvc.MeResponse, error) {
	l := adminservicelogic.NewMeLogic(ctx, s.svcCtx)
	return l.Me(in)
}

// 查询角色菜单。
func (s *AdminServiceServer) Menus(ctx context.Context, in *adminsvc.MenusRequest) (*adminsvc.MenusResponse, error) {
	l := adminservicelogic.NewMenusLogic(ctx, s.svcCtx)
	return l.Menus(in)
}

// 查询操作日志。
func (s *AdminServiceServer) ListOperationLogs(ctx context.Context, in *adminsvc.OperationLogListRequest) (*adminsvc.OperationLogListResponse, error) {
	l := adminservicelogic.NewListOperationLogsLogic(ctx, s.svcCtx)
	return l.ListOperationLogs(in)
}

// 查询用户列表。
func (s *AdminServiceServer) ListUsers(ctx context.Context, in *adminsvc.UserListRequest) (*adminsvc.UserListResponse, error) {
	l := adminservicelogic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

// 查询用户详情。
func (s *AdminServiceServer) GetUser(ctx context.Context, in *adminsvc.UserDetailRequest) (*adminsvc.User, error) {
	l := adminservicelogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 查询司机审核列表。
func (s *AdminServiceServer) ListDriverCertifications(ctx context.Context, in *adminsvc.DriverCertificationListRequest) (*adminsvc.DriverCertificationListResponse, error) {
	l := adminservicelogic.NewListDriverCertificationsLogic(ctx, s.svcCtx)
	return l.ListDriverCertifications(in)
}

// 查询司机审核详情。
func (s *AdminServiceServer) GetDriverCertification(ctx context.Context, in *adminsvc.DriverCertificationDetailRequest) (*adminsvc.DriverCertification, error) {
	l := adminservicelogic.NewGetDriverCertificationLogic(ctx, s.svcCtx)
	return l.GetDriverCertification(in)
}

// 审核通过司机认证。
func (s *AdminServiceServer) ApproveDriverCertification(ctx context.Context, in *adminsvc.AuditDriverCertificationRequest) (*adminsvc.CommonResponse, error) {
	l := adminservicelogic.NewApproveDriverCertificationLogic(ctx, s.svcCtx)
	return l.ApproveDriverCertification(in)
}

// 驳回司机认证。
func (s *AdminServiceServer) RejectDriverCertification(ctx context.Context, in *adminsvc.AuditDriverCertificationRequest) (*adminsvc.CommonResponse, error) {
	l := adminservicelogic.NewRejectDriverCertificationLogic(ctx, s.svcCtx)
	return l.RejectDriverCertification(in)
}

// 查询订单列表。
func (s *AdminServiceServer) ListOrders(ctx context.Context, in *adminsvc.OrderListRequest) (*adminsvc.OrderListResponse, error) {
	l := adminservicelogic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

// 查询订单详情。
func (s *AdminServiceServer) GetOrder(ctx context.Context, in *adminsvc.OrderDetailRequest) (*adminsvc.OrderDetail, error) {
	l := adminservicelogic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}
