// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc/usersvc/proto/usersvc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendSMSCodeRequest 发送短信验证码请求。
type SendSMSCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSCodeRequest) Reset() {
	*x = SendSMSCodeRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSCodeRequest) ProtoMessage() {}

func (x *SendSMSCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSCodeRequest.ProtoReflect.Descriptor instead.
func (*SendSMSCodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{0}
}

func (x *SendSMSCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// SendSMSCodeResponse 发送短信验证码响应。
type SendSMSCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                   // 是否发送成功
	ExpireIn      int64                  `protobuf:"varint,2,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"` // 验证码有效期，单位：秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSCodeResponse) Reset() {
	*x = SendSMSCodeResponse{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSCodeResponse) ProtoMessage() {}

func (x *SendSMSCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSCodeResponse.ProtoReflect.Descriptor instead.
func (*SendSMSCodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{1}
}

func (x *SendSMSCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendSMSCodeResponse) GetExpireIn() int64 {
	if x != nil {
		return x.ExpireIn
	}
	return 0
}

// LoginBySMSRequest 短信验证码登录请求。
type LoginBySMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`   // 短信验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginBySMSRequest) Reset() {
	*x = LoginBySMSRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginBySMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginBySMSRequest) ProtoMessage() {}

func (x *LoginBySMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginBySMSRequest.ProtoReflect.Descriptor instead.
func (*LoginBySMSRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{2}
}

func (x *LoginBySMSRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginBySMSRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// UserInfo 登录态中返回的用户基础信息。
type UserInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          // 用户 ID
	Phone          string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`                                           // 脱敏后的手机号
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`                                     // 昵称
	AvatarUrl      string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`                  // 头像地址
	RealNameStatus string                 `protobuf:"bytes,5,opt,name=real_name_status,json=realNameStatus,proto3" json:"real_name_status,omitempty"` // 实名认证状态：UNVERIFIED/VERIFIED
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetRealNameStatus() string {
	if x != nil {
		return x.RealNameStatus
	}
	return ""
}

// LoginBySMSResponse 短信验证码登录响应。
type LoginBySMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                   // Access Token
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Refresh Token
	IsNewUser     bool                   `protobuf:"varint,3,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`       // 是否为首次创建的用户
	User          *UserInfo              `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                     // 用户基础信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginBySMSResponse) Reset() {
	*x = LoginBySMSResponse{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginBySMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginBySMSResponse) ProtoMessage() {}

func (x *LoginBySMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginBySMSResponse.ProtoReflect.Descriptor instead.
func (*LoginBySMSResponse) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{4}
}

func (x *LoginBySMSResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginBySMSResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginBySMSResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

func (x *LoginBySMSResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// RefreshTokenRequest 刷新令牌请求。
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Refresh Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// RefreshTokenResponse 刷新令牌响应。
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                   // 新的 Access Token
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // 新的 Refresh Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// LogoutRequest 注销请求。
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 当前 Access Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// LogoutResponse 注销响应。
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否注销成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetProfileRequest 查询个人中心资料请求。
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{9}
}

func (x *GetProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetProfileResponse 查询个人中心资料响应。
type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 用户基础信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{10}
}

func (x *GetProfileResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// SubmitRealNameRequest 提交实名信息请求。
type SubmitRealNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`        // 用户 ID
	RealName      string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`   // 真实姓名
	IdCardNo      string                 `protobuf:"bytes,3,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"` // 身份证号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRealNameRequest) Reset() {
	*x = SubmitRealNameRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRealNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRealNameRequest) ProtoMessage() {}

func (x *SubmitRealNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRealNameRequest.ProtoReflect.Descriptor instead.
func (*SubmitRealNameRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitRealNameRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitRealNameRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *SubmitRealNameRequest) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

// SubmitRealNameResponse 提交实名信息响应。
type SubmitRealNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 更新后的用户基础信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRealNameResponse) Reset() {
	*x = SubmitRealNameResponse{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRealNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRealNameResponse) ProtoMessage() {}

func (x *SubmitRealNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRealNameResponse.ProtoReflect.Descriptor instead.
func (*SubmitRealNameResponse) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitRealNameResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// AddressInfo 表示乘客常用地址信息。
type AddressInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 地址 ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户 ID
	ContactName   string                 `protobuf:"bytes,3,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`    // 联系人姓名
	ContactPhone  string                 `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"` // 联系人手机号
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`                                       // 地址标签：home/work/other
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`                               // 详细地址
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`                         // 经度
	Latitude      float64                `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`                           // 纬度
	IsDefault     bool                   `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`         // 是否默认地址
	Sort          int32                  `protobuf:"varint,10,opt,name=sort,proto3" json:"sort,omitempty"`                                   // 排序值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{13}
}

func (x *AddressInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddressInfo) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *AddressInfo) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *AddressInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AddressInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddressInfo) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *AddressInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// CreateAddressRequest 新增常用地址请求。
type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户 ID
	ContactName   string                 `protobuf:"bytes,2,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`    // 联系人姓名
	ContactPhone  string                 `protobuf:"bytes,3,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"` // 联系人手机号
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`                                       // 地址标签
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                               // 详细地址
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`                         // 经度
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`                           // 纬度
	IsDefault     bool                   `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`         // 是否默认地址
	Sort          int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`                                    // 排序值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{14}
}

func (x *CreateAddressRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAddressRequest) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *CreateAddressRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *CreateAddressRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CreateAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAddressRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateAddressRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateAddressRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *CreateAddressRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// ListAddressesRequest 查询常用地址列表请求。
type ListAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesRequest) Reset() {
	*x = ListAddressesRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesRequest) ProtoMessage() {}

func (x *ListAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListAddressesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{15}
}

func (x *ListAddressesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// ListAddressesResponse 常用地址列表响应。
type ListAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AddressInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 地址列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesResponse) Reset() {
	*x = ListAddressesResponse{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesResponse) ProtoMessage() {}

func (x *ListAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesResponse.ProtoReflect.Descriptor instead.
func (*ListAddressesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{16}
}

func (x *ListAddressesResponse) GetList() []*AddressInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// UpdateAddressRequest 更新常用地址请求。
type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 地址 ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户 ID
	ContactName   string                 `protobuf:"bytes,3,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`    // 联系人姓名
	ContactPhone  string                 `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"` // 联系人手机号
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`                                       // 地址标签
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`                               // 详细地址
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`                         // 经度
	Latitude      float64                `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`                           // 纬度
	IsDefault     bool                   `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`         // 是否默认地址
	Sort          int32                  `protobuf:"varint,10,opt,name=sort,proto3" json:"sort,omitempty"`                                   // 排序值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateAddressRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAddressRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAddressRequest) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *UpdateAddressRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *UpdateAddressRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UpdateAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateAddressRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateAddressRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateAddressRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *UpdateAddressRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// DeleteAddressRequest 删除常用地址请求。
type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                       // 地址 ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteAddressRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteAddressRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// DeleteAddressResponse 删除常用地址响应。
type DeleteAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否删除成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResponse) Reset() {
	*x = DeleteAddressResponse{}
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResponse) ProtoMessage() {}

func (x *DeleteAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_usersvc_proto_usersvc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteAddressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_usersvc_proto_usersvc_proto protoreflect.FileDescriptor

const file_rpc_usersvc_proto_usersvc_proto_rawDesc = "" +
	"\n" +
	"\x1frpc/usersvc/proto/usersvc.proto\x12\ausersvc\"*\n" +
	"\x12SendSMSCodeRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"L\n" +
	"\x13SendSMSCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\texpire_in\x18\x02 \x01(\x03R\bexpireIn\"=\n" +
	"\x11LoginBySMSRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x9e\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12(\n" +
	"\x10real_name_status\x18\x05 \x01(\tR\x0erealNameStatus\"\x96\x01\n" +
	"\x12LoginBySMSResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1e\n" +
	"\vis_new_user\x18\x03 \x01(\bR\tisNewUser\x12%\n" +
	"\x04user\x18\x04 \x01(\v2\x11.usersvc.UserInfoR\x04user\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"Q\n" +
	"\x14RefreshTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"%\n" +
	"\rLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\";\n" +
	"\x12GetProfileResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.usersvc.UserInfoR\x04user\"k\n" +
	"\x15SubmitRealNameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x1c\n" +
	"\n" +
	"id_card_no\x18\x03 \x01(\tR\bidCardNo\"?\n" +
	"\x16SubmitRealNameResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.usersvc.UserInfoR\x04user\"\x97\x02\n" +
	"\vAddressInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\fcontact_name\x18\x03 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\bR\tisDefault\x12\x12\n" +
	"\x04sort\x18\n" +
	" \x01(\x05R\x04sort\"\x90\x02\n" +
	"\x14CreateAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fcontact_name\x18\x02 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\x03 \x01(\tR\fcontactPhone\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\"/\n" +
	"\x14ListAddressesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"A\n" +
	"\x15ListAddressesResponse\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.usersvc.AddressInfoR\x04list\"\xa0\x02\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\fcontact_name\x18\x03 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\bR\tisDefault\x12\x12\n" +
	"\x04sort\x18\n" +
	" \x01(\x05R\x04sort\"?\n" +
	"\x14DeleteAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"1\n" +
	"\x15DeleteAddressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe5\x05\n" +
	"\x04User\x12H\n" +
	"\vSendSMSCode\x12\x1b.usersvc.SendSMSCodeRequest\x1a\x1c.usersvc.SendSMSCodeResponse\x12E\n" +
	"\n" +
	"LoginBySMS\x12\x1a.usersvc.LoginBySMSRequest\x1a\x1b.usersvc.LoginBySMSResponse\x12K\n" +
	"\fRefreshToken\x12\x1c.usersvc.RefreshTokenRequest\x1a\x1d.usersvc.RefreshTokenResponse\x129\n" +
	"\x06Logout\x12\x16.usersvc.LogoutRequest\x1a\x17.usersvc.LogoutResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.usersvc.GetProfileRequest\x1a\x1b.usersvc.GetProfileResponse\x12Q\n" +
	"\x0eSubmitRealName\x12\x1e.usersvc.SubmitRealNameRequest\x1a\x1f.usersvc.SubmitRealNameResponse\x12D\n" +
	"\rCreateAddress\x12\x1d.usersvc.CreateAddressRequest\x1a\x14.usersvc.AddressInfo\x12N\n" +
	"\rListAddresses\x12\x1d.usersvc.ListAddressesRequest\x1a\x1e.usersvc.ListAddressesResponse\x12D\n" +
	"\rUpdateAddress\x12\x1d.usersvc.UpdateAddressRequest\x1a\x14.usersvc.AddressInfo\x12N\n" +
	"\rDeleteAddress\x12\x1d.usersvc.DeleteAddressRequest\x1a\x1e.usersvc.DeleteAddressResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_rpc_usersvc_proto_usersvc_proto_rawDescOnce sync.Once
	file_rpc_usersvc_proto_usersvc_proto_rawDescData []byte
)

func file_rpc_usersvc_proto_usersvc_proto_rawDescGZIP() []byte {
	file_rpc_usersvc_proto_usersvc_proto_rawDescOnce.Do(func() {
		file_rpc_usersvc_proto_usersvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_usersvc_proto_usersvc_proto_rawDesc), len(file_rpc_usersvc_proto_usersvc_proto_rawDesc)))
	})
	return file_rpc_usersvc_proto_usersvc_proto_rawDescData
}

var file_rpc_usersvc_proto_usersvc_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_rpc_usersvc_proto_usersvc_proto_goTypes = []any{
	(*SendSMSCodeRequest)(nil),     // 0: usersvc.SendSMSCodeRequest
	(*SendSMSCodeResponse)(nil),    // 1: usersvc.SendSMSCodeResponse
	(*LoginBySMSRequest)(nil),      // 2: usersvc.LoginBySMSRequest
	(*UserInfo)(nil),               // 3: usersvc.UserInfo
	(*LoginBySMSResponse)(nil),     // 4: usersvc.LoginBySMSResponse
	(*RefreshTokenRequest)(nil),    // 5: usersvc.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),   // 6: usersvc.RefreshTokenResponse
	(*LogoutRequest)(nil),          // 7: usersvc.LogoutRequest
	(*LogoutResponse)(nil),         // 8: usersvc.LogoutResponse
	(*GetProfileRequest)(nil),      // 9: usersvc.GetProfileRequest
	(*GetProfileResponse)(nil),     // 10: usersvc.GetProfileResponse
	(*SubmitRealNameRequest)(nil),  // 11: usersvc.SubmitRealNameRequest
	(*SubmitRealNameResponse)(nil), // 12: usersvc.SubmitRealNameResponse
	(*AddressInfo)(nil),            // 13: usersvc.AddressInfo
	(*CreateAddressRequest)(nil),   // 14: usersvc.CreateAddressRequest
	(*ListAddressesRequest)(nil),   // 15: usersvc.ListAddressesRequest
	(*ListAddressesResponse)(nil),  // 16: usersvc.ListAddressesResponse
	(*UpdateAddressRequest)(nil),   // 17: usersvc.UpdateAddressRequest
	(*DeleteAddressRequest)(nil),   // 18: usersvc.DeleteAddressRequest
	(*DeleteAddressResponse)(nil),  // 19: usersvc.DeleteAddressResponse
}
var file_rpc_usersvc_proto_usersvc_proto_depIdxs = []int32{
	3,  // 0: usersvc.LoginBySMSResponse.user:type_name -> usersvc.UserInfo
	3,  // 1: usersvc.GetProfileResponse.user:type_name -> usersvc.UserInfo
	3,  // 2: usersvc.SubmitRealNameResponse.user:type_name -> usersvc.UserInfo
	13, // 3: usersvc.ListAddressesResponse.list:type_name -> usersvc.AddressInfo
	0,  // 4: usersvc.User.SendSMSCode:input_type -> usersvc.SendSMSCodeRequest
	2,  // 5: usersvc.User.LoginBySMS:input_type -> usersvc.LoginBySMSRequest
	5,  // 6: usersvc.User.RefreshToken:input_type -> usersvc.RefreshTokenRequest
	7,  // 7: usersvc.User.Logout:input_type -> usersvc.LogoutRequest
	9,  // 8: usersvc.User.GetProfile:input_type -> usersvc.GetProfileRequest
	11, // 9: usersvc.User.SubmitRealName:input_type -> usersvc.SubmitRealNameRequest
	14, // 10: usersvc.User.CreateAddress:input_type -> usersvc.CreateAddressRequest
	15, // 11: usersvc.User.ListAddresses:input_type -> usersvc.ListAddressesRequest
	17, // 12: usersvc.User.UpdateAddress:input_type -> usersvc.UpdateAddressRequest
	18, // 13: usersvc.User.DeleteAddress:input_type -> usersvc.DeleteAddressRequest
	1,  // 14: usersvc.User.SendSMSCode:output_type -> usersvc.SendSMSCodeResponse
	4,  // 15: usersvc.User.LoginBySMS:output_type -> usersvc.LoginBySMSResponse
	6,  // 16: usersvc.User.RefreshToken:output_type -> usersvc.RefreshTokenResponse
	8,  // 17: usersvc.User.Logout:output_type -> usersvc.LogoutResponse
	10, // 18: usersvc.User.GetProfile:output_type -> usersvc.GetProfileResponse
	12, // 19: usersvc.User.SubmitRealName:output_type -> usersvc.SubmitRealNameResponse
	13, // 20: usersvc.User.CreateAddress:output_type -> usersvc.AddressInfo
	16, // 21: usersvc.User.ListAddresses:output_type -> usersvc.ListAddressesResponse
	13, // 22: usersvc.User.UpdateAddress:output_type -> usersvc.AddressInfo
	19, // 23: usersvc.User.DeleteAddress:output_type -> usersvc.DeleteAddressResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_usersvc_proto_usersvc_proto_init() }
func file_rpc_usersvc_proto_usersvc_proto_init() {
	if File_rpc_usersvc_proto_usersvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_usersvc_proto_usersvc_proto_rawDesc), len(file_rpc_usersvc_proto_usersvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_usersvc_proto_usersvc_proto_goTypes,
		DependencyIndexes: file_rpc_usersvc_proto_usersvc_proto_depIdxs,
		MessageInfos:      file_rpc_usersvc_proto_usersvc_proto_msgTypes,
	}.Build()
	File_rpc_usersvc_proto_usersvc_proto = out.File
	file_rpc_usersvc_proto_usersvc_proto_goTypes = nil
	file_rpc_usersvc_proto_usersvc_proto_depIdxs = nil
}
