// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: driversvc.proto

package server

import (
	"context"

	"XiaoLong-Ridy/rpc/driversvc/internal/logic"
	"XiaoLong-Ridy/rpc/driversvc/internal/svc"
	"XiaoLong-Ridy/rpc/driversvc/proto"
)

type DriversvcServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedDriversvcServer
}

func NewDriversvcServer(svcCtx *svc.ServiceContext) *DriversvcServer {
	return &DriversvcServer{
		svcCtx: svcCtx,
	}
}

// 司机主表 CRUD（仅司机增删改查）
func (s *DriversvcServer) CreateDriver(ctx context.Context, in *proto.CreateDriverRequest) (*proto.CreateDriverResponse, error) {
	l := logic.NewCreateDriverLogic(ctx, s.svcCtx)
	return l.CreateDriver(in)
}

func (s *DriversvcServer) UpdateDriver(ctx context.Context, in *proto.UpdateDriverRequest) (*proto.UpdateDriverResponse, error) {
	l := logic.NewUpdateDriverLogic(ctx, s.svcCtx)
	return l.UpdateDriver(in)
}

func (s *DriversvcServer) DeleteDriver(ctx context.Context, in *proto.DeleteDriverRequest) (*proto.DeleteDriverResponse, error) {
	l := logic.NewDeleteDriverLogic(ctx, s.svcCtx)
	return l.DeleteDriver(in)
}

func (s *DriversvcServer) GetDriver(ctx context.Context, in *proto.GetDriverRequest) (*proto.GetDriverResponse, error) {
	l := logic.NewGetDriverLogic(ctx, s.svcCtx)
	return l.GetDriver(in)
}
