// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: driversvc.proto

package server

import (
	"context"

	"XiaoLong-Ridy/rpc/driversvc/internal/logic"
	"XiaoLong-Ridy/rpc/driversvc/internal/svc"
	"XiaoLong-Ridy/rpc/driversvc/proto"
)

type DriversvcServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedDriversvcServer
}

func NewDriversvcServer(svcCtx *svc.ServiceContext) *DriversvcServer {
	return &DriversvcServer{
		svcCtx: svcCtx,
	}
}

// 司机主表 CRUD（仅司机增删改查）
func (s *DriversvcServer) CreateDriver(ctx context.Context, in *proto.CreateDriverRequest) (*proto.CreateDriverResponse, error) {
	l := logic.NewCreateDriverLogic(ctx, s.svcCtx)
	return l.CreateDriver(in)
}

// RegisterDriver 处理司机自注册请求，与管理员创建使用独立 RPC 方法但共享账号校验和落库逻辑。
func (s *DriversvcServer) RegisterDriver(ctx context.Context, in *proto.CreateDriverRequest) (*proto.CreateDriverResponse, error) {
	l := logic.NewCreateDriverLogic(ctx, s.svcCtx)
	return l.CreateDriver(in)
}

func (s *DriversvcServer) UpdateDriver(ctx context.Context, in *proto.UpdateDriverRequest) (*proto.UpdateDriverResponse, error) {
	l := logic.NewUpdateDriverLogic(ctx, s.svcCtx)
	return l.UpdateDriver(in)
}

func (s *DriversvcServer) DeleteDriver(ctx context.Context, in *proto.DeleteDriverRequest) (*proto.DeleteDriverResponse, error) {
	l := logic.NewDeleteDriverLogic(ctx, s.svcCtx)
	return l.DeleteDriver(in)
}

func (s *DriversvcServer) GetDriver(ctx context.Context, in *proto.GetDriverRequest) (*proto.GetDriverResponse, error) {
	l := logic.NewGetDriverLogic(ctx, s.svcCtx)
	return l.GetDriver(in)
}

// 按手机号查询司机（登录场景使用，返回含密码哈希与状态）
func (s *DriversvcServer) GetDriverByPhone(ctx context.Context, in *proto.GetDriverByPhoneRequest) (*proto.GetDriverByPhoneResponse, error) {
	l := logic.NewGetDriverByPhoneLogic(ctx, s.svcCtx)
	return l.GetDriverByPhone(in)
}

// 司机上线：将听单状态置为在线（1）。
func (s *DriversvcServer) SetDriverOnline(ctx context.Context, in *proto.SetDriverOnlineRequest) (*proto.SetDriverOnlineResponse, error) {
	l := logic.NewSetDriverOnlineLogic(ctx, s.svcCtx)
	return l.SetDriverOnline(in)
}

// 司机下线：将听单状态置为离线（0）。
func (s *DriversvcServer) SetDriverOffline(ctx context.Context, in *proto.SetDriverOfflineRequest) (*proto.SetDriverOfflineResponse, error) {
	l := logic.NewSetDriverOfflineLogic(ctx, s.svcCtx)
	return l.SetDriverOffline(in)
}

// 车辆 CRUD（司机绑定车辆增删改查）
func (s *DriversvcServer) CreateVehicle(ctx context.Context, in *proto.CreateVehicleRequest) (*proto.CreateVehicleResponse, error) {
	l := logic.NewCreateVehicleLogic(ctx, s.svcCtx)
	return l.CreateVehicle(in)
}

func (s *DriversvcServer) UpdateVehicle(ctx context.Context, in *proto.UpdateVehicleRequest) (*proto.UpdateVehicleResponse, error) {
	l := logic.NewUpdateVehicleLogic(ctx, s.svcCtx)
	return l.UpdateVehicle(in)
}

func (s *DriversvcServer) DeleteVehicle(ctx context.Context, in *proto.DeleteVehicleRequest) (*proto.DeleteVehicleResponse, error) {
	l := logic.NewDeleteVehicleLogic(ctx, s.svcCtx)
	return l.DeleteVehicle(in)
}

func (s *DriversvcServer) GetVehicle(ctx context.Context, in *proto.GetVehicleRequest) (*proto.GetVehicleResponse, error) {
	l := logic.NewGetVehicleLogic(ctx, s.svcCtx)
	return l.GetVehicle(in)
}

// 司机列表：分页 + 可选状态/关键字过滤。
func (s *DriversvcServer) ListDrivers(ctx context.Context, in *proto.ListDriversRequest) (*proto.ListDriversResponse, error) {
	l := logic.NewListDriversLogic(ctx, s.svcCtx)
	return l.ListDrivers(in)
}

// 司机登录：校验手机号、账号状态与密码，成功返回 JWT。
func (s *DriversvcServer) Login(ctx context.Context, in *proto.LoginRequest) (*proto.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 附近司机查询：按经纬度 + 半径查找在线司机，供派单引擎调用。
func (s *DriversvcServer) ListNearbyDrivers(ctx context.Context, in *proto.ListNearbyDriversRequest) (*proto.ListNearbyDriversResponse, error) {
	l := logic.NewListNearbyDriversLogic(ctx, s.svcCtx)
	return l.ListNearbyDrivers(in)
}

// AI 智能优质司机推荐：查询指定司机的综合推荐得分与各项维度指标，供司机端展示与派单权重参考。
func (s *DriversvcServer) GetDriverAiScore(ctx context.Context, in *proto.GetDriverAiScoreRequest) (*proto.GetDriverAiScoreResponse, error) {
	l := logic.NewGetDriverAiScoreLogic(ctx, s.svcCtx)
	return l.GetDriverAiScore(in)
}

// UploadCertification 处理司机资质上传：直传 MinIO 并落库，返回资质记录与审核状态。
func (s *DriversvcServer) UploadCertification(ctx context.Context, in *proto.UploadCertificationRequest) (*proto.UploadCertificationResponse, error) {
	l := logic.NewUploadCertificationLogic(ctx, s.svcCtx)
	return l.UploadCertification(in)
}

// GetCertification 按司机 ID 查询资质记录与审核状态。
func (s *DriversvcServer) GetCertification(ctx context.Context, in *proto.GetCertificationRequest) (*proto.GetCertificationResponse, error) {
	l := logic.NewGetCertificationLogic(ctx, s.svcCtx)
	return l.GetCertification(in)
}

// Heartbeat 处理司机心跳上报：刷新在线状态保活并判定多端互踢。
func (s *DriversvcServer) Heartbeat(ctx context.Context, in *proto.HeartbeatRequest) (*proto.HeartbeatResponse, error) {
	l := logic.NewHeartbeatLogic(ctx, s.svcCtx)
	return l.Heartbeat(in)
}

// ApproveCertification 审核通过司机资质：更新资质状态并同步司机/车辆状态为正常。
func (s *DriversvcServer) ApproveCertification(ctx context.Context, in *proto.AuditCertificationRequest) (*proto.CommonResponse, error) {
	l := logic.NewApproveCertificationLogic(ctx, s.svcCtx)
	return l.ApproveCertification(in)
}

// RejectCertification 审核驳回司机资质：更新资质状态为驳回并记录备注。
func (s *DriversvcServer) RejectCertification(ctx context.Context, in *proto.AuditCertificationRequest) (*proto.CommonResponse, error) {
	l := logic.NewRejectCertificationLogic(ctx, s.svcCtx)
	return l.RejectCertification(in)
}
