// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: driversvc.proto

package server

import (
	"context"

	"XiaoLong-Ridy/rpc/driversvc/internal/logic"
	"XiaoLong-Ridy/rpc/driversvc/internal/svc"
	__proto "XiaoLong-Ridy/rpc/driversvc/proto"
)

type DriversvcServer struct {
	svcCtx *svc.ServiceContext
	__proto.UnimplementedDriversvcServer
}

func NewDriversvcServer(svcCtx *svc.ServiceContext) *DriversvcServer {
	return &DriversvcServer{
		svcCtx: svcCtx,
	}
}

// 创建司机账号：后台或内部链路创建司机，初始状态为待审核。
func (s *DriversvcServer) CreateDriver(ctx context.Context, in *__proto.CreateDriverRequest) (*__proto.CreateDriverResponse, error) {
	l := logic.NewCreateDriverLogic(ctx, s.svcCtx)
	return l.CreateDriver(in)
}

// 司机自注册：公开注册入口使用，与创建司机共享校验和落库逻辑。
func (s *DriversvcServer) RegisterDriver(ctx context.Context, in *__proto.CreateDriverRequest) (*__proto.CreateDriverResponse, error) {
	l := logic.NewCreateDriverLogic(ctx, s.svcCtx)
	return l.CreateDriver(in)
}

// 更新司机资料：仅更新 optional 字段中显式传入的内容。
func (s *DriversvcServer) UpdateDriver(ctx context.Context, in *__proto.UpdateDriverRequest) (*__proto.UpdateDriverResponse, error) {
	l := logic.NewUpdateDriverLogic(ctx, s.svcCtx)
	return l.UpdateDriver(in)
}

// 删除司机：按司机 ID 软删除账号。
func (s *DriversvcServer) DeleteDriver(ctx context.Context, in *__proto.DeleteDriverRequest) (*__proto.DeleteDriverResponse, error) {
	l := logic.NewDeleteDriverLogic(ctx, s.svcCtx)
	return l.DeleteDriver(in)
}

// 查询司机详情：按司机 ID 返回司机基础资料。
func (s *DriversvcServer) GetDriver(ctx context.Context, in *__proto.GetDriverRequest) (*__proto.GetDriverResponse, error) {
	l := logic.NewGetDriverLogic(ctx, s.svcCtx)
	return l.GetDriver(in)
}

// 按手机号查询司机：登录链路使用，返回账号状态与密码哈希。
func (s *DriversvcServer) GetDriverByPhone(ctx context.Context, in *__proto.GetDriverByPhoneRequest) (*__proto.GetDriverByPhoneResponse, error) {
	l := logic.NewGetDriverByPhoneLogic(ctx, s.svcCtx)
	return l.GetDriverByPhone(in)
}

// 司机上线：绑定设备、写入位置并将听单状态置为在线。
func (s *DriversvcServer) SetDriverOnline(ctx context.Context, in *__proto.SetDriverOnlineRequest) (*__proto.SetDriverOnlineResponse, error) {
	l := logic.NewSetDriverOnlineLogic(ctx, s.svcCtx)
	return l.SetDriverOnline(in)
}

// 司机下线：校验设备并将听单状态置为离线。
func (s *DriversvcServer) SetDriverOffline(ctx context.Context, in *__proto.SetDriverOfflineRequest) (*__proto.SetDriverOfflineResponse, error) {
	l := logic.NewSetDriverOfflineLogic(ctx, s.svcCtx)
	return l.SetDriverOffline(in)
}

// 上报位置：刷新司机在线保活并落库最新经纬度。
func (s *DriversvcServer) ReportLocation(ctx context.Context, in *__proto.ReportLocationRequest) (*__proto.ReportLocationResponse, error) {
	l := logic.NewReportLocationLogic(ctx, s.svcCtx)
	return l.ReportLocation(in)
}

// 设置司机服务状态：供行程开始/结束等内部链路同步在线、行程中、离线状态。
func (s *DriversvcServer) SetDriverServiceStatus(ctx context.Context, in *__proto.SetDriverServiceStatusRequest) (*__proto.SetDriverServiceStatusResponse, error) {
	l := logic.NewSetDriverServiceStatusLogic(ctx, s.svcCtx)
	return l.SetDriverServiceStatus(in)
}

// 心跳：刷新在线 TTL，判定多端互踢并返回服务器时间。
func (s *DriversvcServer) Heartbeat(ctx context.Context, in *__proto.HeartbeatRequest) (*__proto.HeartbeatResponse, error) {
	l := logic.NewHeartbeatLogic(ctx, s.svcCtx)
	return l.Heartbeat(in)
}

// 创建车辆：绑定司机车辆，初始状态为待审核。
func (s *DriversvcServer) CreateVehicle(ctx context.Context, in *__proto.CreateVehicleRequest) (*__proto.CreateVehicleResponse, error) {
	l := logic.NewCreateVehicleLogic(ctx, s.svcCtx)
	return l.CreateVehicle(in)
}

// 更新车辆：仅更新 optional 字段中显式传入的内容。
func (s *DriversvcServer) UpdateVehicle(ctx context.Context, in *__proto.UpdateVehicleRequest) (*__proto.UpdateVehicleResponse, error) {
	l := logic.NewUpdateVehicleLogic(ctx, s.svcCtx)
	return l.UpdateVehicle(in)
}

// 删除车辆：按车辆 ID 删除车辆记录。
func (s *DriversvcServer) DeleteVehicle(ctx context.Context, in *__proto.DeleteVehicleRequest) (*__proto.DeleteVehicleResponse, error) {
	l := logic.NewDeleteVehicleLogic(ctx, s.svcCtx)
	return l.DeleteVehicle(in)
}

// 查询车辆详情：按车辆 ID 返回车辆基础资料。
func (s *DriversvcServer) GetVehicle(ctx context.Context, in *__proto.GetVehicleRequest) (*__proto.GetVehicleResponse, error) {
	l := logic.NewGetVehicleLogic(ctx, s.svcCtx)
	return l.GetVehicle(in)
}

// 查询司机列表：分页返回司机记录，支持状态与关键字筛选。
func (s *DriversvcServer) ListDrivers(ctx context.Context, in *__proto.ListDriversRequest) (*__proto.ListDriversResponse, error) {
	l := logic.NewListDriversLogic(ctx, s.svcCtx)
	return l.ListDrivers(in)
}

// 密码登录：校验手机号、密码和账号状态，成功返回 JWT。
func (s *DriversvcServer) Login(ctx context.Context, in *__proto.LoginRequest) (*__proto.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 短信登录：验证码由 API 层校验，RPC 负责按手机号签发登录态。
func (s *DriversvcServer) LoginBySMS(ctx context.Context, in *__proto.LoginBySMSRequest) (*__proto.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.LoginBySMS(in)
}

// 查询附近司机：按经纬度、半径和数量限制返回在线司机列表。
func (s *DriversvcServer) ListNearbyDrivers(ctx context.Context, in *__proto.ListNearbyDriversRequest) (*__proto.ListNearbyDriversResponse, error) {
	l := logic.NewListNearbyDriversLogic(ctx, s.svcCtx)
	return l.ListNearbyDrivers(in)
}

// 查询司机 AI 推荐分：返回综合分、等级、影响因子和降级状态。
func (s *DriversvcServer) GetDriverAiScore(ctx context.Context, in *__proto.GetDriverAiScoreRequest) (*__proto.GetDriverAiScoreResponse, error) {
	l := logic.NewGetDriverAiScoreLogic(ctx, s.svcCtx)
	return l.GetDriverAiScore(in)
}

// 上传资质：接收身份证、驾驶证、行驶证图片并写入资质记录。
func (s *DriversvcServer) UploadCertification(ctx context.Context, in *__proto.UploadCertificationRequest) (*__proto.UploadCertificationResponse, error) {
	l := logic.NewUploadCertificationLogic(ctx, s.svcCtx)
	return l.UploadCertification(in)
}

// 查询资质：按司机 ID 查询最近一次资质记录。
func (s *DriversvcServer) GetCertification(ctx context.Context, in *__proto.GetCertificationRequest) (*__proto.GetCertificationResponse, error) {
	l := logic.NewGetCertificationLogic(ctx, s.svcCtx)
	return l.GetCertification(in)
}

// 审核通过资质：将资质、司机和车辆状态推进为正常。
func (s *DriversvcServer) ApproveCertification(ctx context.Context, in *__proto.AuditCertificationRequest) (*__proto.CommonResponse, error) {
	l := logic.NewApproveCertificationLogic(ctx, s.svcCtx)
	return l.ApproveCertification(in)
}

// 审核驳回资质：记录驳回原因并保持司机/车辆非正常状态。
func (s *DriversvcServer) RejectCertification(ctx context.Context, in *__proto.AuditCertificationRequest) (*__proto.CommonResponse, error) {
	l := logic.NewRejectCertificationLogic(ctx, s.svcCtx)
	return l.RejectCertification(in)
}

// 发起提现申请：司机提交提现金额与收款账户，初始状态为申请中。
func (s *DriversvcServer) CreateWithdraw(ctx context.Context, in *__proto.CreateWithdrawRequest) (*__proto.CreateWithdrawResponse, error) {
	l := logic.NewCreateWithdrawLogic(ctx, s.svcCtx)
	return l.CreateWithdraw(in)
}

// 查询我的提现记录：按司机 ID 分页返回提现申请与打款状态。
func (s *DriversvcServer) ListWithdraws(ctx context.Context, in *__proto.ListWithdrawsRequest) (*__proto.ListWithdrawsResponse, error) {
	l := logic.NewListWithdrawsLogic(ctx, s.svcCtx)
	return l.ListWithdraws(in)
}
