// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: paysvc.proto

package server

import (
	"context"

	"XiaoLong-Ridy/rpc/paysvc/internal/logic"
	"XiaoLong-Ridy/rpc/paysvc/internal/svc"
	"XiaoLong-Ridy/rpc/paysvc/proto"
)

type PayServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedPayServer
}

func NewPayServer(svcCtx *svc.ServiceContext) *PayServer {
	return &PayServer{
		svcCtx: svcCtx,
	}
}

// 支付预下单：创建支付单并调第三方下单（本期为 mock）。
func (s *PayServer) CreatePayment(ctx context.Context, in *proto.CreatePaymentRequest) (*proto.CreatePaymentResponse, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}
