// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpc/ordersvc/proto/ordersvc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_WAIT_ACCEPT OrderStatus = 1 // 待接单
	OrderStatus_ORDER_STATUS_ACCEPTED    OrderStatus = 2 // 已接单
	OrderStatus_ORDER_STATUS_ON_TRIP     OrderStatus = 3 // 行程中
	OrderStatus_ORDER_STATUS_WAIT_PAY    OrderStatus = 4 // 待支付
	OrderStatus_ORDER_STATUS_COMPLETED   OrderStatus = 5 // 已完成
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 6 // 已取消
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_WAIT_ACCEPT",
		2: "ORDER_STATUS_ACCEPTED",
		3: "ORDER_STATUS_ON_TRIP",
		4: "ORDER_STATUS_WAIT_PAY",
		5: "ORDER_STATUS_COMPLETED",
		6: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_WAIT_ACCEPT": 1,
		"ORDER_STATUS_ACCEPTED":    2,
		"ORDER_STATUS_ON_TRIP":     3,
		"ORDER_STATUS_WAIT_PAY":    4,
		"ORDER_STATUS_COMPLETED":   5,
		"ORDER_STATUS_CANCELLED":   6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_ordersvc_proto_ordersvc_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_rpc_ordersvc_proto_ordersvc_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_ordersvc_proto_ordersvc_proto_rawDescGZIP(), []int{0}
}

// 添加订单：乘客叫车后创建一笔订单，状态初始为待接单。
type CreateOrderRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CarType             int32                  `protobuf:"varint,2,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"` // 车型：1特惠快车 2快车 3拼车
	FromAddress         string                 `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	FromLongitude       float64                `protobuf:"fixed64,4,opt,name=from_longitude,json=fromLongitude,proto3" json:"from_longitude,omitempty"`
	FromLatitude        float64                `protobuf:"fixed64,5,opt,name=from_latitude,json=fromLatitude,proto3" json:"from_latitude,omitempty"`
	ToAddress           string                 `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	ToLongitude         float64                `protobuf:"fixed64,7,opt,name=to_longitude,json=toLongitude,proto3" json:"to_longitude,omitempty"`
	ToLatitude          float64                `protobuf:"fixed64,8,opt,name=to_latitude,json=toLatitude,proto3" json:"to_latitude,omitempty"`
	EstimatedDistanceM  int64                  `protobuf:"varint,9,opt,name=estimated_distance_m,json=estimatedDistanceM,proto3" json:"estimated_distance_m,omitempty"`     // 预估距离（米）
	EstimatedDurationS  int64                  `protobuf:"varint,10,opt,name=estimated_duration_s,json=estimatedDurationS,proto3" json:"estimated_duration_s,omitempty"`    // 预估时长（秒）
	EstimatedPriceCents int64                  `protobuf:"varint,11,opt,name=estimated_price_cents,json=estimatedPriceCents,proto3" json:"estimated_price_cents,omitempty"` // 预估价格（分）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_rpc_ordersvc_proto_ordersvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ordersvc_proto_ordersvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_rpc_ordersvc_proto_ordersvc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetCarType() int32 {
	if x != nil {
		return x.CarType
	}
	return 0
}

func (x *CreateOrderRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetFromLongitude() float64 {
	if x != nil {
		return x.FromLongitude
	}
	return 0
}

func (x *CreateOrderRequest) GetFromLatitude() float64 {
	if x != nil {
		return x.FromLatitude
	}
	return 0
}

func (x *CreateOrderRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetToLongitude() float64 {
	if x != nil {
		return x.ToLongitude
	}
	return 0
}

func (x *CreateOrderRequest) GetToLatitude() float64 {
	if x != nil {
		return x.ToLatitude
	}
	return 0
}

func (x *CreateOrderRequest) GetEstimatedDistanceM() int64 {
	if x != nil {
		return x.EstimatedDistanceM
	}
	return 0
}

func (x *CreateOrderRequest) GetEstimatedDurationS() int64 {
	if x != nil {
		return x.EstimatedDurationS
	}
	return 0
}

func (x *CreateOrderRequest) GetEstimatedPriceCents() int64 {
	if x != nil {
		return x.EstimatedPriceCents
	}
	return 0
}

type CreateOrderResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderId             int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo             string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	EstimatedPriceCents int64                  `protobuf:"varint,3,opt,name=estimated_price_cents,json=estimatedPriceCents,proto3" json:"estimated_price_cents,omitempty"`
	Status              OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=ordersvc.OrderStatus" json:"status,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix 秒
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_rpc_ordersvc_proto_ordersvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ordersvc_proto_ordersvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_ordersvc_proto_ordersvc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderResponse) GetEstimatedPriceCents() int64 {
	if x != nil {
		return x.EstimatedPriceCents
	}
	return 0
}

func (x *CreateOrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *CreateOrderResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_rpc_ordersvc_proto_ordersvc_proto protoreflect.FileDescriptor

const file_rpc_ordersvc_proto_ordersvc_proto_rawDesc = "" +
	"\n" +
	"!rpc/ordersvc/proto/ordersvc.proto\x12\bordersvc\"\xb2\x03\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bcar_type\x18\x02 \x01(\x05R\acarType\x12!\n" +
	"\ffrom_address\x18\x03 \x01(\tR\vfromAddress\x12%\n" +
	"\x0efrom_longitude\x18\x04 \x01(\x01R\rfromLongitude\x12#\n" +
	"\rfrom_latitude\x18\x05 \x01(\x01R\ffromLatitude\x12\x1d\n" +
	"\n" +
	"to_address\x18\x06 \x01(\tR\ttoAddress\x12!\n" +
	"\fto_longitude\x18\a \x01(\x01R\vtoLongitude\x12\x1f\n" +
	"\vto_latitude\x18\b \x01(\x01R\n" +
	"toLatitude\x120\n" +
	"\x14estimated_distance_m\x18\t \x01(\x03R\x12estimatedDistanceM\x120\n" +
	"\x14estimated_duration_s\x18\n" +
	" \x01(\x03R\x12estimatedDurationS\x122\n" +
	"\x15estimated_price_cents\x18\v \x01(\x03R\x13estimatedPriceCents\"\xcd\x01\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x122\n" +
	"\x15estimated_price_cents\x18\x03 \x01(\x03R\x13estimatedPriceCents\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.ordersvc.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt*\xd1\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ORDER_STATUS_WAIT_ACCEPT\x10\x01\x12\x19\n" +
	"\x15ORDER_STATUS_ACCEPTED\x10\x02\x12\x18\n" +
	"\x14ORDER_STATUS_ON_TRIP\x10\x03\x12\x19\n" +
	"\x15ORDER_STATUS_WAIT_PAY\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x062S\n" +
	"\x05Order\x12J\n" +
	"\vCreateOrder\x12\x1c.ordersvc.CreateOrderRequest\x1a\x1d.ordersvc.CreateOrderResponseB\x1fZ\x1dXiaoLong-Ridy/rpc/ordersvc/pbb\x06proto3"

var (
	file_rpc_ordersvc_proto_ordersvc_proto_rawDescOnce sync.Once
	file_rpc_ordersvc_proto_ordersvc_proto_rawDescData []byte
)

func file_rpc_ordersvc_proto_ordersvc_proto_rawDescGZIP() []byte {
	file_rpc_ordersvc_proto_ordersvc_proto_rawDescOnce.Do(func() {
		file_rpc_ordersvc_proto_ordersvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_ordersvc_proto_ordersvc_proto_rawDesc), len(file_rpc_ordersvc_proto_ordersvc_proto_rawDesc)))
	})
	return file_rpc_ordersvc_proto_ordersvc_proto_rawDescData
}

var file_rpc_ordersvc_proto_ordersvc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_ordersvc_proto_ordersvc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_ordersvc_proto_ordersvc_proto_goTypes = []any{
	(OrderStatus)(0),            // 0: ordersvc.OrderStatus
	(*CreateOrderRequest)(nil),  // 1: ordersvc.CreateOrderRequest
	(*CreateOrderResponse)(nil), // 2: ordersvc.CreateOrderResponse
}
var file_rpc_ordersvc_proto_ordersvc_proto_depIdxs = []int32{
	0, // 0: ordersvc.CreateOrderResponse.status:type_name -> ordersvc.OrderStatus
	1, // 1: ordersvc.Order.CreateOrder:input_type -> ordersvc.CreateOrderRequest
	2, // 2: ordersvc.Order.CreateOrder:output_type -> ordersvc.CreateOrderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_ordersvc_proto_ordersvc_proto_init() }
func file_rpc_ordersvc_proto_ordersvc_proto_init() {
	if File_rpc_ordersvc_proto_ordersvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_ordersvc_proto_ordersvc_proto_rawDesc), len(file_rpc_ordersvc_proto_ordersvc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_ordersvc_proto_ordersvc_proto_goTypes,
		DependencyIndexes: file_rpc_ordersvc_proto_ordersvc_proto_depIdxs,
		EnumInfos:         file_rpc_ordersvc_proto_ordersvc_proto_enumTypes,
		MessageInfos:      file_rpc_ordersvc_proto_ordersvc_proto_msgTypes,
	}.Build()
	File_rpc_ordersvc_proto_ordersvc_proto = out.File
	file_rpc_ordersvc_proto_ordersvc_proto_goTypes = nil
	file_rpc_ordersvc_proto_ordersvc_proto_depIdxs = nil
}
