// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: pricesvc.proto

package server

import (
	"context"

	"XiaoLong-Ridy/rpc/pricesvc/internal/logic"
	"XiaoLong-Ridy/rpc/pricesvc/internal/svc"
	"XiaoLong-Ridy/rpc/pricesvc/proto"
)

type PriceServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedPriceServer
}

func NewPriceServer(svcCtx *svc.ServiceContext) *PriceServer {
	return &PriceServer{
		svcCtx: svcCtx,
	}
}

// 行程价格预估：根据计价规则 + 里程/时长估算费用。
func (s *PriceServer) EstimatePrice(ctx context.Context, in *proto.EstimatePriceRequest) (*proto.EstimatePriceResponse, error) {
	l := logic.NewEstimatePriceLogic(ctx, s.svcCtx)
	return l.EstimatePrice(in)
}

// 优惠券抵扣计算：根据优惠券计算折扣与实付金额。
func (s *PriceServer) CalculateDiscount(ctx context.Context, in *proto.CalculateDiscountRequest) (*proto.CalculateDiscountResponse, error) {
	l := logic.NewCalculateDiscountLogic(ctx, s.svcCtx)
	return l.CalculateDiscount(in)
}
