// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: rpc/chatsvc/proto/chatsvc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrCreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CallerType    int32                  `protobuf:"varint,2,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"` // 1司机 2乘客（由 api/chat 根据 JWT 注入）
	CallerId      int64                  `protobuf:"varint,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`       // 调用方账号ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateConversationRequest) Reset() {
	*x = GetOrCreateConversationRequest{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateConversationRequest) ProtoMessage() {}

func (x *GetOrCreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateConversationRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrCreateConversationRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetOrCreateConversationRequest) GetCallerType() int32 {
	if x != nil {
		return x.CallerType
	}
	return 0
}

func (x *GetOrCreateConversationRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

type GetOrCreateConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	OrderId        int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo        string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Status         int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // 会话状态 1进行中 2已归档 3已关闭
	LastMsg        string                 `protobuf:"bytes,5,opt,name=last_msg,json=lastMsg,proto3" json:"last_msg,omitempty"`
	LastMsgAt      int64                  `protobuf:"varint,6,opt,name=last_msg_at,json=lastMsgAt,proto3" json:"last_msg_at,omitempty"` // Unix 秒
	Unread         int32                  `protobuf:"varint,7,opt,name=unread,proto3" json:"unread,omitempty"`                          // 调用方未读数
	Peer           *PeerInfo              `protobuf:"bytes,8,opt,name=peer,proto3" json:"peer,omitempty"`
	Opened         bool                   `protobuf:"varint,9,opt,name=opened,proto3" json:"opened,omitempty"` // 是否可聊天（等待接单/已关闭时为 false）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrCreateConversationResponse) Reset() {
	*x = GetOrCreateConversationResponse{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateConversationResponse) ProtoMessage() {}

func (x *GetOrCreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateConversationResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrCreateConversationResponse) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetOrCreateConversationResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetOrCreateConversationResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrCreateConversationResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetOrCreateConversationResponse) GetLastMsg() string {
	if x != nil {
		return x.LastMsg
	}
	return ""
}

func (x *GetOrCreateConversationResponse) GetLastMsgAt() int64 {
	if x != nil {
		return x.LastMsgAt
	}
	return 0
}

func (x *GetOrCreateConversationResponse) GetUnread() int32 {
	if x != nil {
		return x.Unread
	}
	return 0
}

func (x *GetOrCreateConversationResponse) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *GetOrCreateConversationResponse) GetOpened() bool {
	if x != nil {
		return x.Opened
	}
	return false
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // driver / passenger
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PeerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Cursor         int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`                           // 上次拉到的最大消息 id，首拉为 0
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                             // 上限 20
	CallerType     int32                  `protobuf:"varint,4,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"` // 1司机 2乘客（api/chat 注入，用于权限校验）
	CallerId       int64                  `protobuf:"varint,5,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{3}
}

func (x *ListMessagesRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ListMessagesRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetCallerType() int32 {
	if x != nil {
		return x.CallerType
	}
	return 0
}

func (x *ListMessagesRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *ListMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ChatMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	OrderId        int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SenderType     int32                  `protobuf:"varint,4,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"` // 1司机 2乘客
	SenderId       int64                  `protobuf:"varint,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MsgType        int32                  `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"` // 1文本 2快捷短语
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId    string                 `protobuf:"bytes,8,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	CreateAt       int64                  `protobuf:"varint,9,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"` // Unix 秒
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatMessage) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ChatMessage) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ChatMessage) GetSenderType() int32 {
	if x != nil {
		return x.SenderType
	}
	return 0
}

func (x *ChatMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *ChatMessage) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderType     int32                  `protobuf:"varint,2,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"` // 1司机 2乘客
	SenderId       int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MsgType        int32                  `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"` // 1文本 2快捷短语
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId    string                 `protobuf:"bytes,6,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendMessageRequest) GetSenderType() int32 {
	if x != nil {
		return x.SenderType
	}
	return 0
}

func (x *SendMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CreateAt      int64                  `protobuf:"varint,2,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"` // Unix 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendMessageResponse) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	CallerType     int32                  `protobuf:"varint,2,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"` // 1司机 2乘客
	CallerId       int64                  `protobuf:"varint,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{8}
}

func (x *MarkReadRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MarkReadRequest) GetCallerType() int32 {
	if x != nil {
		return x.CallerType
	}
	return 0
}

func (x *MarkReadRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatsvc_proto_chatsvc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP(), []int{9}
}

func (x *MarkReadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_rpc_chatsvc_proto_chatsvc_proto protoreflect.FileDescriptor

const file_rpc_chatsvc_proto_chatsvc_proto_rawDesc = "" +
	"\n" +
	"\x1frpc/chatsvc/proto/chatsvc.proto\x12\achatsvc\"y\n" +
	"\x1eGetOrCreateConversationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1f\n" +
	"\vcaller_type\x18\x02 \x01(\x05R\n" +
	"callerType\x12\x1b\n" +
	"\tcaller_id\x18\x03 \x01(\x03R\bcallerId\"\xaa\x02\n" +
	"\x1fGetOrCreateConversationResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x19\n" +
	"\blast_msg\x18\x05 \x01(\tR\alastMsg\x12\x1e\n" +
	"\vlast_msg_at\x18\x06 \x01(\x03R\tlastMsgAt\x12\x16\n" +
	"\x06unread\x18\a \x01(\x05R\x06unread\x12%\n" +
	"\x04peer\x18\b \x01(\v2\x11.chatsvc.PeerInfoR\x04peer\x12\x16\n" +
	"\x06opened\x18\t \x01(\bR\x06opened\"B\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xaa\x01\n" +
	"\x13ListMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vcaller_type\x18\x04 \x01(\x05R\n" +
	"callerType\x12\x1b\n" +
	"\tcaller_id\x18\x05 \x01(\x03R\bcallerId\"\x84\x01\n" +
	"\x14ListMessagesResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.chatsvc.ChatMessageR\bmessages\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x95\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x1f\n" +
	"\vsender_type\x18\x04 \x01(\x05R\n" +
	"senderType\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\x03R\bsenderId\x12\x19\n" +
	"\bmsg_type\x18\x06 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\b \x01(\tR\vclientMsgId\x12\x1b\n" +
	"\tcreate_at\x18\t \x01(\x03R\bcreateAt\"\xd4\x01\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x1f\n" +
	"\vsender_type\x18\x02 \x01(\x05R\n" +
	"senderType\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x19\n" +
	"\bmsg_type\x18\x04 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x06 \x01(\tR\vclientMsgId\"Q\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1b\n" +
	"\tcreate_at\x18\x02 \x01(\x03R\bcreateAt\"x\n" +
	"\x0fMarkReadRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x1f\n" +
	"\vcaller_type\x18\x02 \x01(\x05R\n" +
	"callerType\x12\x1b\n" +
	"\tcaller_id\x18\x03 \x01(\x03R\bcallerId\"\"\n" +
	"\x10MarkReadResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xcc\x02\n" +
	"\x04Chat\x12l\n" +
	"\x17GetOrCreateConversation\x12'.chatsvc.GetOrCreateConversationRequest\x1a(.chatsvc.GetOrCreateConversationResponse\x12K\n" +
	"\fListMessages\x12\x1c.chatsvc.ListMessagesRequest\x1a\x1d.chatsvc.ListMessagesResponse\x12H\n" +
	"\vSendMessage\x12\x1b.chatsvc.SendMessageRequest\x1a\x1c.chatsvc.SendMessageResponse\x12?\n" +
	"\bMarkRead\x12\x18.chatsvc.MarkReadRequest\x1a\x19.chatsvc.MarkReadResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_rpc_chatsvc_proto_chatsvc_proto_rawDescOnce sync.Once
	file_rpc_chatsvc_proto_chatsvc_proto_rawDescData []byte
)

func file_rpc_chatsvc_proto_chatsvc_proto_rawDescGZIP() []byte {
	file_rpc_chatsvc_proto_chatsvc_proto_rawDescOnce.Do(func() {
		file_rpc_chatsvc_proto_chatsvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_chatsvc_proto_chatsvc_proto_rawDesc), len(file_rpc_chatsvc_proto_chatsvc_proto_rawDesc)))
	})
	return file_rpc_chatsvc_proto_chatsvc_proto_rawDescData
}

var file_rpc_chatsvc_proto_chatsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_chatsvc_proto_chatsvc_proto_goTypes = []any{
	(*GetOrCreateConversationRequest)(nil),  // 0: chatsvc.GetOrCreateConversationRequest
	(*GetOrCreateConversationResponse)(nil), // 1: chatsvc.GetOrCreateConversationResponse
	(*PeerInfo)(nil),                        // 2: chatsvc.PeerInfo
	(*ListMessagesRequest)(nil),             // 3: chatsvc.ListMessagesRequest
	(*ListMessagesResponse)(nil),            // 4: chatsvc.ListMessagesResponse
	(*ChatMessage)(nil),                     // 5: chatsvc.ChatMessage
	(*SendMessageRequest)(nil),              // 6: chatsvc.SendMessageRequest
	(*SendMessageResponse)(nil),             // 7: chatsvc.SendMessageResponse
	(*MarkReadRequest)(nil),                 // 8: chatsvc.MarkReadRequest
	(*MarkReadResponse)(nil),                // 9: chatsvc.MarkReadResponse
}
var file_rpc_chatsvc_proto_chatsvc_proto_depIdxs = []int32{
	2, // 0: chatsvc.GetOrCreateConversationResponse.peer:type_name -> chatsvc.PeerInfo
	5, // 1: chatsvc.ListMessagesResponse.messages:type_name -> chatsvc.ChatMessage
	0, // 2: chatsvc.Chat.GetOrCreateConversation:input_type -> chatsvc.GetOrCreateConversationRequest
	3, // 3: chatsvc.Chat.ListMessages:input_type -> chatsvc.ListMessagesRequest
	6, // 4: chatsvc.Chat.SendMessage:input_type -> chatsvc.SendMessageRequest
	8, // 5: chatsvc.Chat.MarkRead:input_type -> chatsvc.MarkReadRequest
	1, // 6: chatsvc.Chat.GetOrCreateConversation:output_type -> chatsvc.GetOrCreateConversationResponse
	4, // 7: chatsvc.Chat.ListMessages:output_type -> chatsvc.ListMessagesResponse
	7, // 8: chatsvc.Chat.SendMessage:output_type -> chatsvc.SendMessageResponse
	9, // 9: chatsvc.Chat.MarkRead:output_type -> chatsvc.MarkReadResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_chatsvc_proto_chatsvc_proto_init() }
func file_rpc_chatsvc_proto_chatsvc_proto_init() {
	if File_rpc_chatsvc_proto_chatsvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_chatsvc_proto_chatsvc_proto_rawDesc), len(file_rpc_chatsvc_proto_chatsvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_chatsvc_proto_chatsvc_proto_goTypes,
		DependencyIndexes: file_rpc_chatsvc_proto_chatsvc_proto_depIdxs,
		MessageInfos:      file_rpc_chatsvc_proto_chatsvc_proto_msgTypes,
	}.Build()
	File_rpc_chatsvc_proto_chatsvc_proto = out.File
	file_rpc_chatsvc_proto_chatsvc_proto_goTypes = nil
	file_rpc_chatsvc_proto_chatsvc_proto_depIdxs = nil
}
