// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rpc/locationsvc/locationsvc.proto

package locationsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	LocationService_ReverseGeocode_FullMethodName = "/locationsvc.LocationService/ReverseGeocode"
	LocationService_POISearch_FullMethodName      = "/locationsvc.LocationService/POISearch"
	LocationService_RoutePlan_FullMethodName      = "/locationsvc.LocationService/RoutePlan"
)

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 位置服务
type LocationServiceClient interface {
	// 逆地址解析（经纬度 → 地址）
	ReverseGeocode(ctx context.Context, in *ReverseGeocodeReq, opts ...grpc.CallOption) (*ReverseGeocodeResp, error)
	// POI 搜索
	POISearch(ctx context.Context, in *POISearchReq, opts ...grpc.CallOption) (*POISearchResp, error)
	// 路径规划（计算距离和预计时间）
	RoutePlan(ctx context.Context, in *RoutePlanReq, opts ...grpc.CallOption) (*RoutePlanResp, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) ReverseGeocode(ctx context.Context, in *ReverseGeocodeReq, opts ...grpc.CallOption) (*ReverseGeocodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseGeocodeResp)
	err := c.cc.Invoke(ctx, LocationService_ReverseGeocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) POISearch(ctx context.Context, in *POISearchReq, opts ...grpc.CallOption) (*POISearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(POISearchResp)
	err := c.cc.Invoke(ctx, LocationService_POISearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) RoutePlan(ctx context.Context, in *RoutePlanReq, opts ...grpc.CallOption) (*RoutePlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutePlanResp)
	err := c.cc.Invoke(ctx, LocationService_RoutePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility
//
// 位置服务
type LocationServiceServer interface {
	// 逆地址解析（经纬度 → 地址）
	ReverseGeocode(context.Context, *ReverseGeocodeReq) (*ReverseGeocodeResp, error)
	// POI 搜索
	POISearch(context.Context, *POISearchReq) (*POISearchResp, error)
	// 路径规划（计算距离和预计时间）
	RoutePlan(context.Context, *RoutePlanReq) (*RoutePlanResp, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLocationServiceServer struct {
}

func (UnimplementedLocationServiceServer) ReverseGeocode(context.Context, *ReverseGeocodeReq) (*ReverseGeocodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseGeocode not implemented")
}
func (UnimplementedLocationServiceServer) POISearch(context.Context, *POISearchReq) (*POISearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POISearch not implemented")
}
func (UnimplementedLocationServiceServer) RoutePlan(context.Context, *RoutePlanReq) (*RoutePlanResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoutePlan not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_ReverseGeocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseGeocodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).ReverseGeocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_ReverseGeocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).ReverseGeocode(ctx, req.(*ReverseGeocodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_POISearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(POISearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).POISearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_POISearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).POISearch(ctx, req.(*POISearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_RoutePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutePlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).RoutePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_RoutePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).RoutePlan(ctx, req.(*RoutePlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "locationsvc.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReverseGeocode",
			Handler:    _LocationService_ReverseGeocode_Handler,
		},
		{
			MethodName: "POISearch",
			Handler:    _LocationService_POISearch_Handler,
		},
		{
			MethodName: "RoutePlan",
			Handler:    _LocationService_RoutePlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/locationsvc/locationsvc.proto",
}
