-- 补齐优惠券模型新增字段，兼容历史数据库结构。
ALTER TABLE coupon
  ADD COLUMN IF NOT EXISTS car_type TINYINT NOT NULL DEFAULT 0 AFTER threshold_amount,
  ADD COLUMN IF NOT EXISTS city_code VARCHAR(20) NOT NULL DEFAULT '' AFTER car_type;

ALTER TABLE user_coupon
  ADD COLUMN IF NOT EXISTS locked_order_id BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER order_id,
  ADD COLUMN IF NOT EXISTS locked_at DATETIME NULL AFTER used_at,
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER expire_at,
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
