<script setup>
// 管理后台统一业务工作区：根据当前路由选择真实接口、字段列和可用操作。
// 页面不保存业务副本，所有查询和写操作完成后重新从后台读取，避免显示过期状态。
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search, Plus, Refresh, Download, Check, Close } from '@element-plus/icons-vue'
import { usersApi, driversApi, ordersApi, marketingApi, workOrdersApi, statisticsApi, riskApi, logsApi } from '../../api/modules'
import { text, pageData } from '../../utils/format'

const route = useRoute(); const router = useRouter(); const loading = ref(false); const rows = ref([]); const total = ref(0); const page = ref(1); const pageSize = ref(20); const detail = ref(null); const dialog = ref(false); const dialogType = ref(''); const form = reactive({})
const filters = reactive({ keyword: '', status: '', audit_status: '', type: '', start_time: '', end_time: '', abnormal_type: '', target_type: '', target_id: '', export_type: 'orders' })
const title = computed(() => route.meta.title || '工作台');
const kind = computed(() => route.path.split('/')[1] || 'dashboard');
// routeKey 用完整静态路径区分普通订单与异常订单，避免被首段 orders 误判。
const routeKey = computed(() => route.path === '/orders/abnormal' ? 'orders/abnormal' : kind.value)
const isAbnormalOrders = computed(() => routeKey.value === 'orders/abnormal')
const isStatistics = computed(() => kind.value === 'statistics')
const isDetail = computed(() => !!route.params.id || !!route.params.taskNo)
const columns = computed(() => {
  const map = {
    users: [['id','ID'],['phone','手机号'],['nickname','昵称'],['real_name','实名'],['status','状态'],['created_at','注册时间']],
    'driver-certifications': [['id','审核单'],['driver_name','司机'],['driver_phone','手机号'],['plate_no','车牌'],['audit_status','审核状态'],['created_at','提交时间']],
    orders: [['order_no','订单号'],['user_id','用户'],['driver_id','司机'],['from_address','出发地'],['to_address','目的地'],['estimated_price','预估金额'],['status','状态'],['created_at','下单时间']],
    'orders/abnormal': [['order_no','订单号'],['abnormal_type','异常类型'],['abnormal_reason','异常原因'],['payment_status','支付状态'],['dispatch_status','派单状态'],['status','订单状态'],['created_at','下单时间']],
    coupons: [['name','券名称'],['type','类型'],['face_value','面额'],['threshold_amount','门槛'],['total_count','库存'],['received_count','已发放'],['status','状态']],
    'coupon-issue-tasks': [['task_no','任务号'],['coupon_id','优惠券'],['target_type','目标'],['total_count','总量'],['success_count','成功'],['fail_count','失败'],['status','状态']],
    'price-rules': [['name','规则名称'],['city_code','城市'],['car_type','车型'],['base_price','起步价'],['status','状态'],['effective_at','生效时间']],
    'promotion-activities': [['name','活动名称'],['type','类型'],['start_at','开始时间'],['end_at','结束时间'],['status','状态']],
    'work-orders': [['id','工单号'],['title','标题'],['source_type','来源'],['priority','优先级'],['status','状态'],['created_at','创建时间']],
    'export-tasks': [['task_no','任务号'],['export_type','类型'],['status','状态'],['failure_reason','失败原因'],['created_at','创建时间']],
    blacklist: [['id','记录号'],['target_type','目标类型'],['target_id','目标 ID'],['reason','原因'],['status','状态'],['created_at','加入时间']],
    'risk-hits': [['id','记录号'],['target_type','目标类型'],['target_id','目标 ID'],['scene','场景'],['risk_level','风险等级'],['hit_reason','命中原因'],['created_at','时间']],
    'operation-logs': [['id','日志号'],['admin_id','管理员'],['module','模块'],['action','动作'],['target_type','目标'],['detail','详情'],['created_at','时间']],
  }
  return map[kind.value] || []
})
const api = computed(() => ({ users: usersApi.list, 'driver-certifications': driversApi.list, orders: ordersApi.list, 'orders/abnormal': ordersApi.abnormal, coupons: marketingApi.coupons, 'coupon-issue-tasks': marketingApi.issueTasks, 'price-rules': marketingApi.priceRules, 'promotion-activities': marketingApi.activities, 'work-orders': workOrdersApi.list, 'export-tasks': statisticsApi.exports, blacklist: riskApi.blacklist, 'risk-hits': riskApi.hits, 'operation-logs': logsApi.list }[routeKey.value] || (() => Promise.resolve({ list: [], total: 0 }))))
const label = (key, value) => { const maps = { status: { 1:'正常/待接单',2:'已接单/冻结',3:'行程中',4:'待支付',5:'已完成',6:'已取消' }, audit_status:{1:'待审核',2:'已通过',3:'已驳回'}, type:{1:'满减/拉新',2:'折扣',3:'立减/活动'}, risk_level:{1:'低',2:'中',3:'高'}, abnormal_type:{cancel:'取消异常',payment:'支付异常',dispatch:'派单异常'}, payment_status:{1:'待支付',2:'已支付',3:'支付异常'}, dispatch_status:{1:'待派单',2:'已派单',3:'派单异常'} }; return maps[key]?.[value] || text(value) }
const load = async () => { if (kind.value === 'dashboard' || isStatistics.value || isDetail.value) return; loading.value = true; try { const data = await api.value({ ...filters, page: page.value, page_size: pageSize.value }); const p = pageData(data); rows.value = p.list; total.value = p.total } finally { loading.value = false } }
const reset = () => { Object.keys(filters).forEach(k => { filters[k] = k === 'export_type' ? 'orders' : '' }); page.value = 1; load() }
const loadDetail = async () => { const id = route.params.id; if (kind.value === 'users') detail.value = await usersApi.detail(id); else if (kind.value === 'driver-certifications') detail.value = await driversApi.detail(id); else if (kind.value === 'orders') detail.value = await ordersApi.detail(id); else if (kind.value === 'price-rules') detail.value = await marketingApi.priceRule(id); else if (kind.value === 'work-orders') detail.value = await workOrdersApi.detail(id); else if (kind.value === 'export-tasks') detail.value = await statisticsApi.exportDetail(route.params.taskNo); }
const openDetail = async (row) => { const id = row.id || row.task_no; const path = kind.value === 'export-tasks' ? `/export-tasks/${id}` : `/${kind.value}/${id}`; await router.push(path) }
// action 打开指定业务动作弹窗，并仅预填对应接口允许的字段，避免把列表回传的只读字段提交给服务端。
const action = async (name, row = {}) => {
  dialogType.value = name
  Object.keys(form).forEach(k => delete form[k])
  form.id = row.id
  form.row = row
  const coupon = () => ({ name: row.name, type: row.type, face_value: row.face_value, discount: row.discount, threshold_amount: row.threshold_amount, total_count: row.total_count, per_user_limit: row.per_user_limit, valid_start_at: row.valid_start_at, valid_end_at: row.valid_end_at, status: row.status })
  const priceRule = () => ({ name: row.name, city_code: row.city_code, car_type: row.car_type, base_price: row.base_price, base_distance_km: row.base_distance_km, per_km_price: row.per_km_price, per_minute_price: row.per_minute_price, night_start_time: row.night_start_time, night_end_time: row.night_end_time, night_surcharge: row.night_surcharge, dynamic_max_factor: row.dynamic_max_factor, status: row.status, effective_at: row.effective_at, expire_at: row.expire_at })
  const activity = () => ({ name: row.name, type: row.type, config: row.config, start_at: row.start_at, end_at: row.end_at, status: row.status })
  if (name === 'editCoupon') form.payload = JSON.stringify(coupon(), null, 2)
  if (name === 'issueCoupon') form.payload = JSON.stringify({ target_type: 'explicit_users', target_config: '{"user_ids":[]}' }, null, 2)
  if (name === 'editPriceRule') form.payload = JSON.stringify(priceRule(), null, 2)
  if (name === 'editActivity') form.payload = JSON.stringify(activity(), null, 2)
  if (name === 'workOrderAction') form.payload = JSON.stringify({ action: 'follow', assignee_id: 0, content: '', arbitration_result: '', version: row.version }, null, 2)
  if (name === 'workOrderEvidence') form.payload = JSON.stringify({ evidence_type: 'text', evidence_url: '', content: '' }, null, 2)
  dialog.value = true
}
const openCreate = () => { dialogType.value = 'create'; Object.keys(form).forEach(k => delete form[k]); form.payload = '{}'; dialog.value = true }
// submitAction 根据当前动作调用唯一对应的已开放接口；成功后重查列表或详情，避免乐观更新造成状态过期。
const submitAction = async () => { try { const payload = ['create', 'editCoupon', 'issueCoupon', 'editPriceRule', 'editActivity', 'workOrderAction', 'workOrderEvidence'].includes(dialogType.value) ? JSON.parse(form.payload || '{}') : null; if (dialogType.value === 'create') { if (kind.value === 'coupons') await marketingApi.createCoupon(payload); else if (kind.value === 'price-rules') await marketingApi.createPriceRule(payload); else if (kind.value === 'promotion-activities') await marketingApi.createActivity(payload); else if (kind.value === 'work-orders') await workOrdersApi.create(payload); else if (kind.value === 'blacklist') await riskApi.add(payload); else if (kind.value === 'export-tasks') await statisticsApi.createExport(payload); }
if (dialogType.value === 'editCoupon') await marketingApi.updateCoupon(form.id, payload); if (dialogType.value === 'issueCoupon') await marketingApi.issueCoupon(form.id, payload); if (dialogType.value === 'editPriceRule') await marketingApi.updatePriceRule(form.id, payload); if (dialogType.value === 'editActivity') await marketingApi.updateActivity(form.id, payload); if (dialogType.value === 'workOrderAction') await workOrdersApi.action(form.id, payload); if (dialogType.value === 'workOrderEvidence') await workOrdersApi.evidence(form.id, payload); if (dialogType.value === 'freeze' || dialogType.value === 'unfreeze') await (dialogType.value === 'freeze' ? usersApi.freeze : usersApi.unfreeze)(form.id, { reason: form.reason || '', remark: form.remark || '' }); if (dialogType.value === 'approve' || dialogType.value === 'reject') await (dialogType.value === 'approve' ? driversApi.approve : driversApi.reject)(form.id, { remark: form.remark || '' }); if (dialogType.value === 'cancel') await ordersApi.cancel(form.id, { reason: form.reason || '' }); if (dialogType.value === 'disableCoupon') await marketingApi.disableCoupon(form.id); if (dialogType.value === 'release') await riskApi.release(form.id, { reason: form.reason || '' }); if (dialogType.value === 'enableRule') await marketingApi.enablePriceRule(form.id); if (dialogType.value === 'disableRule') await marketingApi.disablePriceRule(form.id); if (dialogType.value === 'publish') await marketingApi.publishActivity(form.id, { publish_scope: 'all', target_config: '{}' }); if (dialogType.value === 'rollback') await marketingApi.rollbackActivity(form.id, { publish_scope: '', target_config: '{}' }); dialog.value = false; ElMessage.success('操作成功'); if (isDetail.value) await loadDetail(); else await load() } catch (error) { if (error instanceof SyntaxError) ElMessage.error('JSON 配置格式不正确') } }
const dashboard = ref({ overview: {}, orders: {}, coupons: {} });
const statisticsRange = ref([])
// statisticsParams 统一生成统计接口时间范围；未选择时默认近 30 天。
const statisticsParams = () => { if (statisticsRange.value?.length === 2) return { start_time: statisticsRange.value[0], end_time: statisticsRange.value[1] }; const end = new Date(); const start = new Date(end); start.setDate(end.getDate() - 30); const fmt = (d) => d.toISOString().slice(0, 19).replace('T', ' '); return { start_time: fmt(start), end_time: fmt(end) } }
// loadDashboard 并发请求三个真实统计接口，工作台和数据统计页共用同一份数据。
const loadDashboard = async () => { loading.value = true; try { const params = statisticsParams(); const [overview, orders, coupons] = await Promise.all([statisticsApi.overview(params), statisticsApi.orders(params), statisticsApi.coupons(params)]); dashboard.value = { overview: overview || {}, orders: orders || {}, coupons: coupons || {} } } finally { loading.value = false } }
onMounted(() => kind.value === 'dashboard' || isStatistics.value ? loadDashboard() : isDetail.value ? loadDetail() : load()); watch(() => route.path, () => { detail.value = null; page.value = 1; kind.value === 'dashboard' || isStatistics.value ? loadDashboard() : isDetail.value ? loadDetail() : load() });
</script>

<template>
  <section class="console" v-loading="loading">
    <template v-if="kind === 'dashboard' || isStatistics">
      <div class="hero"><div><span class="eyebrow">运营数据中心</span><h1>{{ isStatistics ? '数据统计' : '工作台' }}</h1><p>{{ isStatistics ? '按时间范围查看用户、订单与营销核心指标' : '实时掌握用户、订单与营销运营状态' }}</p></div><div class="statistics-actions"><el-date-picker v-if="isStatistics" v-model="statisticsRange" type="datetimerange" value-format="YYYY-MM-DD HH:mm:ss" start-placeholder="开始时间" end-placeholder="结束时间" /><el-button :icon="Refresh" @click="loadDashboard">刷新数据</el-button></div></div>
      <div class="metric-grid"><div v-for="item in [{k:'order_count',t:'订单总量'},{k:'completed_order_count',t:'完成订单'},{k:'user_count',t:'用户总量'},{k:'driver_count',t:'司机总量'},{k:'gmv',t:'GMV'}]" :key="item.k" class="metric"><span>{{ item.t }}</span><strong>{{ text(dashboard.overview[item.k]) }}</strong><small>来自实时统计接口</small></div></div>
      <div class="panel-grid"><div class="panel"><div class="panel-title">订单运营</div><div class="stat-line"><span>完成率</span><b>{{ text(dashboard.orders.completion_rate) }}</b></div><div class="stat-line"><span>取消率</span><b>{{ text(dashboard.orders.cancel_rate) }}</b></div><div class="stat-line"><span>异常订单</span><b>{{ text(dashboard.overview.abnormal_order_count) }}</b></div></div><div class="panel"><div class="panel-title">优惠券运营</div><div class="stat-line"><span>优惠券模板</span><b>{{ text(dashboard.coupons.coupon_count) }}</b></div><div class="stat-line"><span>已启用</span><b>{{ text(dashboard.coupons.enabled_coupon_count) }}</b></div><div class="stat-line"><span>使用率</span><b>{{ text(dashboard.coupons.use_rate) }}</b></div></div></div>
    </template>
    <template v-else-if="isDetail"><div class="page-head"><div><span class="eyebrow">详情视图</span><h1>{{ title }}</h1></div><div class="head-actions"><el-button v-if="kind === 'work-orders'" type="primary" @click="action('workOrderAction', detail || {})">工单流转</el-button><el-button v-if="kind === 'work-orders'" @click="action('workOrderEvidence', detail || {})">添加证据</el-button><el-button @click="router.back()">返回列表</el-button></div></div><div class="panel detail-json"><pre>{{ JSON.stringify(detail, null, 2) }}</pre></div></template>
    <template v-else>
      <div class="page-head"><div><span class="eyebrow">管理后台 / {{ title }}</span><h1>{{ title }}</h1></div><div class="head-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="['coupons','price-rules','promotion-activities','work-orders','blacklist','export-tasks'].includes(kind)" type="primary" :icon="Plus" @click="openCreate">新建</el-button></div></div>
      <div class="panel filters"><el-input v-model="filters.keyword" placeholder="关键词 / 编号" clearable :prefix-icon="Search" @keyup.enter="load" /><el-select v-if="kind === 'users'" v-model="filters.status" placeholder="用户状态" clearable><el-option label="正常" value="1"/><el-option label="冻结" value="2"/></el-select><el-select v-if="kind === 'driver-certifications'" v-model="filters.audit_status" placeholder="审核状态" clearable><el-option label="待审核" value="1"/><el-option label="已通过" value="2"/><el-option label="已驳回" value="3"/></el-select><el-select v-if="kind === 'orders' && !isAbnormalOrders" v-model="filters.status" placeholder="订单状态" clearable><el-option v-for="(v,k) in {1:'待接单',2:'已接单',3:'行程中',4:'待支付',5:'已完成',6:'已取消'}" :key="k" :label="v" :value="k"/></el-select><el-select v-if="isAbnormalOrders" v-model="filters.abnormal_type" placeholder="异常类型" clearable><el-option label="取消异常" value="cancel"/><el-option label="支付异常" value="payment"/><el-option label="派单异常" value="dispatch"/></el-select><el-button type="primary" @click="page=1;load">查询</el-button><el-button @click="reset">重置</el-button></div>
      <div class="panel table-panel"><el-table :data="rows" stripe empty-text="暂无数据"><el-table-column v-for="c in columns" :key="c[0]" :prop="c[0]" :label="c[1]" min-width="140"><template #default="scope"><span :class="{mono:c[0].includes('id') || c[0].includes('no')}" >{{ label(c[0], scope.row[c[0]]) }}</span></template></el-table-column><el-table-column label="操作" fixed="right" width="320"><template #default="scope"><el-button link type="primary" @click="openDetail(scope.row)">查看</el-button><el-button v-if="kind==='users'" link type="warning" @click="action(scope.row.status==1?'freeze':'unfreeze',scope.row)">{{ scope.row.status==1?'冻结':'解冻' }}</el-button><el-button v-if="kind==='driver-certifications' && scope.row.audit_status==1" link type="success" @click="action('approve',scope.row)">通过</el-button><el-button v-if="kind==='driver-certifications' && scope.row.audit_status==1" link type="danger" @click="action('reject',scope.row)">驳回</el-button><el-button v-if="kind==='orders' && !isAbnormalOrders && ![5,6].includes(scope.row.status)" link type="danger" @click="action('cancel',scope.row)">取消订单</el-button><el-button v-if="kind==='coupons'" link type="primary" @click="action('editCoupon',scope.row)">编辑</el-button><el-button v-if="kind==='coupons' && scope.row.status!=3" link type="success" @click="action('issueCoupon',scope.row)">发券</el-button><el-button v-if="kind==='coupons' && scope.row.status!=3" link type="warning" @click="action('disableCoupon',scope.row)">停用</el-button><el-button v-if="kind==='blacklist' && scope.row.status==1" link type="danger" @click="action('release',scope.row)">解除</el-button><el-button v-if="kind==='price-rules'" link type="primary" @click="action('editPriceRule',scope.row)">编辑</el-button><el-button v-if="kind==='price-rules'" link type="success" @click="action(scope.row.status==2?'disableRule':'enableRule',scope.row)">{{scope.row.status==2?'停用':'启用'}}</el-button><el-button v-if="kind==='promotion-activities'" link type="primary" @click="action('editActivity',scope.row)">编辑</el-button><el-button v-if="kind==='promotion-activities'" link type="warning" @click="action(scope.row.status==2?'rollback':'publish',scope.row)">{{scope.row.status==2?'回滚':'发布'}}</el-button></template></el-table-column></el-table><div class="table-footer"><span>共 {{ total }} 条记录</span><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" layout="prev, pager, next, sizes" @current-change="load" @size-change="load" /></div></div>
    </template>
    <el-dialog v-model="dialog" :title="dialogType === 'create' ? `新建${title}` : dialogType" width="520px"><el-form label-width="90px"><el-form-item v-if="['create','editCoupon','issueCoupon','editPriceRule','editActivity','workOrderAction','workOrderEvidence'].includes(dialogType)" label="请求 JSON"><el-input v-model="form.payload" type="textarea" :rows="10" /></el-form-item><p v-if="dialogType === 'issueCoupon'" class="form-hint">仅支持 explicit_users，target_config 示例：{"user_ids":[1001,1002]}。</p><p v-if="dialogType === 'workOrderAction'" class="form-hint">action 可为 assign、follow、arbitrate、close、reopen；必须保留当前 version。</p><p v-if="dialogType === 'workOrderEvidence'" class="form-hint">evidence_type 可为 track、audio、chat、payment、image、text。</p><el-form-item v-if="['freeze','unfreeze','cancel','release'].includes(dialogType)" label="原因"><el-input v-model="form.reason" type="textarea" /></el-form-item><el-form-item v-if="['freeze','unfreeze','approve','reject'].includes(dialogType)" label="备注"><el-input v-model="form.remark" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="submitAction">确认提交</el-button></template></el-dialog>
  </section>
</template>

<style scoped>
.console{color:#dce7f3}.hero,.page-head{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:24px}.eyebrow{color:#6f879d;font-size:12px;letter-spacing:.08em}.hero h1,.page-head h1{margin:7px 0 4px;font-size:28px;color:#f4f7fb}.hero p{margin:0;color:#8293a5}.statistics-actions{display:flex;align-items:center;gap:10px}.metric-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:16px}.metric,.panel{background:#101d2b;border:1px solid #1d3042;border-radius:10px}.metric{padding:20px}.metric span,.metric small{display:block;color:#8395a7}.metric strong{display:block;color:#fff;font-size:30px;margin:12px 0}.metric small{font-size:12px}.panel-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.panel{padding:18px}.panel-title{font-size:17px;font-weight:700;color:#fff;margin-bottom:15px}.stat-line{display:flex;justify-content:space-between;border-top:1px solid #1c2c3c;padding:15px 0;color:#8ea1b2}.stat-line b{color:#ff8538}.filters{display:flex;gap:10px;align-items:center;margin-bottom:16px}.filters .el-input{width:260px}.filters .el-select{width:160px}.table-panel{padding:0;overflow:hidden}.table-footer{display:flex;justify-content:space-between;align-items:center;padding:14px 18px;color:#8092a4}.mono{font-family:ui-monospace;color:#28b8c9}.detail-json{overflow:auto}.detail-json pre{margin:0;color:#b8c9d7;white-space:pre-wrap}.head-actions{display:flex;gap:10px}.form-hint{margin:-8px 0 14px 90px;color:#8293a5;font-size:12px;line-height:1.5}@media(max-width:1000px){.metric-grid{grid-template-columns:repeat(2,1fr)}.panel-grid{grid-template-columns:1fr}.filters,.statistics-actions{flex-wrap:wrap}}
</style>
