// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rpc/pricesvc/proto/pricesvc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Price_EstimatePrice_FullMethodName        = "/pricesvc.Price/EstimatePrice"
	Price_CalculateDiscount_FullMethodName    = "/pricesvc.Price/CalculateDiscount"
	Price_SaveActualOrderPrice_FullMethodName = "/pricesvc.Price/SaveActualOrderPrice"
	Price_GetOrderPrice_FullMethodName        = "/pricesvc.Price/GetOrderPrice"
	Price_ListPriceRules_FullMethodName       = "/pricesvc.Price/ListPriceRules"
	Price_GetPriceRule_FullMethodName         = "/pricesvc.Price/GetPriceRule"
	Price_CreatePriceRule_FullMethodName      = "/pricesvc.Price/CreatePriceRule"
	Price_UpdatePriceRule_FullMethodName      = "/pricesvc.Price/UpdatePriceRule"
	Price_SetPriceRuleStatus_FullMethodName   = "/pricesvc.Price/SetPriceRuleStatus"
)

// PriceClient is the client API for Price service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 计价服务：行程价格预估、优惠抵扣与实际费用落库。
type PriceClient interface {
	// 行程价格预估：根据计价规则 + 里程/时长估算费用。
	EstimatePrice(ctx context.Context, in *EstimatePriceRequest, opts ...grpc.CallOption) (*EstimatePriceResponse, error)
	// 优惠券抵扣计算：根据优惠券计算折扣与实付金额。
	CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountResponse, error)
	// 实际费用落库：行程结束时由订单模块调用，将实际费用快照写入 order_price。
	SaveActualOrderPrice(ctx context.Context, in *SaveActualOrderPriceRequest, opts ...grpc.CallOption) (*SaveActualOrderPriceResponse, error)
	// 订单价格明细查询：供管理后台按订单ID查询 order_price 快照。
	GetOrderPrice(ctx context.Context, in *GetOrderPriceRequest, opts ...grpc.CallOption) (*OrderPriceInfo, error)
	// 计价规则列表查询。
	ListPriceRules(ctx context.Context, in *PriceRuleListRequest, opts ...grpc.CallOption) (*PriceRuleListResponse, error)
	// 计价规则详情查询。
	GetPriceRule(ctx context.Context, in *PriceRuleDetailRequest, opts ...grpc.CallOption) (*PriceRule, error)
	// 创建计价规则。
	CreatePriceRule(ctx context.Context, in *PriceRuleRequest, opts ...grpc.CallOption) (*CreatePriceRuleResponse, error)
	// 更新计价规则。
	UpdatePriceRule(ctx context.Context, in *PriceRuleRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// 更新计价规则状态。
	SetPriceRuleStatus(ctx context.Context, in *PriceRuleStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type priceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceClient(cc grpc.ClientConnInterface) PriceClient {
	return &priceClient{cc}
}

func (c *priceClient) EstimatePrice(ctx context.Context, in *EstimatePriceRequest, opts ...grpc.CallOption) (*EstimatePriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimatePriceResponse)
	err := c.cc.Invoke(ctx, Price_EstimatePrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceClient) CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateDiscountResponse)
	err := c.cc.Invoke(ctx, Price_CalculateDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceClient) SaveActualOrderPrice(ctx context.Context, in *SaveActualOrderPriceRequest, opts ...grpc.CallOption) (*SaveActualOrderPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveActualOrderPriceResponse)
	err := c.cc.Invoke(ctx, Price_SaveActualOrderPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceClient) GetOrderPrice(ctx context.Context, in *GetOrderPriceRequest, opts ...grpc.CallOption) (*OrderPriceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderPriceInfo)
	err := c.cc.Invoke(ctx, Price_GetOrderPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceClient) ListPriceRules(ctx context.Context, in *PriceRuleListRequest, opts ...grpc.CallOption) (*PriceRuleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceRuleListResponse)
	err := c.cc.Invoke(ctx, Price_ListPriceRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceClient) GetPriceRule(ctx context.Context, in *PriceRuleDetailRequest, opts ...grpc.CallOption) (*PriceRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceRule)
	err := c.cc.Invoke(ctx, Price_GetPriceRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceClient) CreatePriceRule(ctx context.Context, in *PriceRuleRequest, opts ...grpc.CallOption) (*CreatePriceRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePriceRuleResponse)
	err := c.cc.Invoke(ctx, Price_CreatePriceRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceClient) UpdatePriceRule(ctx context.Context, in *PriceRuleRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, Price_UpdatePriceRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceClient) SetPriceRuleStatus(ctx context.Context, in *PriceRuleStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, Price_SetPriceRuleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceServer is the server API for Price service.
// All implementations must embed UnimplementedPriceServer
// for forward compatibility
//
// 计价服务：行程价格预估、优惠抵扣与实际费用落库。
type PriceServer interface {
	// 行程价格预估：根据计价规则 + 里程/时长估算费用。
	EstimatePrice(context.Context, *EstimatePriceRequest) (*EstimatePriceResponse, error)
	// 优惠券抵扣计算：根据优惠券计算折扣与实付金额。
	CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountResponse, error)
	// 实际费用落库：行程结束时由订单模块调用，将实际费用快照写入 order_price。
	SaveActualOrderPrice(context.Context, *SaveActualOrderPriceRequest) (*SaveActualOrderPriceResponse, error)
	// 订单价格明细查询：供管理后台按订单ID查询 order_price 快照。
	GetOrderPrice(context.Context, *GetOrderPriceRequest) (*OrderPriceInfo, error)
	// 计价规则列表查询。
	ListPriceRules(context.Context, *PriceRuleListRequest) (*PriceRuleListResponse, error)
	// 计价规则详情查询。
	GetPriceRule(context.Context, *PriceRuleDetailRequest) (*PriceRule, error)
	// 创建计价规则。
	CreatePriceRule(context.Context, *PriceRuleRequest) (*CreatePriceRuleResponse, error)
	// 更新计价规则。
	UpdatePriceRule(context.Context, *PriceRuleRequest) (*CommonResponse, error)
	// 更新计价规则状态。
	SetPriceRuleStatus(context.Context, *PriceRuleStatusRequest) (*CommonResponse, error)
	mustEmbedUnimplementedPriceServer()
}

// UnimplementedPriceServer must be embedded to have forward compatible implementations.
type UnimplementedPriceServer struct {
}

func (UnimplementedPriceServer) EstimatePrice(context.Context, *EstimatePriceRequest) (*EstimatePriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimatePrice not implemented")
}
func (UnimplementedPriceServer) CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDiscount not implemented")
}
func (UnimplementedPriceServer) SaveActualOrderPrice(context.Context, *SaveActualOrderPriceRequest) (*SaveActualOrderPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveActualOrderPrice not implemented")
}
func (UnimplementedPriceServer) GetOrderPrice(context.Context, *GetOrderPriceRequest) (*OrderPriceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderPrice not implemented")
}
func (UnimplementedPriceServer) ListPriceRules(context.Context, *PriceRuleListRequest) (*PriceRuleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPriceRules not implemented")
}
func (UnimplementedPriceServer) GetPriceRule(context.Context, *PriceRuleDetailRequest) (*PriceRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPriceRule not implemented")
}
func (UnimplementedPriceServer) CreatePriceRule(context.Context, *PriceRuleRequest) (*CreatePriceRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePriceRule not implemented")
}
func (UnimplementedPriceServer) UpdatePriceRule(context.Context, *PriceRuleRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePriceRule not implemented")
}
func (UnimplementedPriceServer) SetPriceRuleStatus(context.Context, *PriceRuleStatusRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPriceRuleStatus not implemented")
}
func (UnimplementedPriceServer) mustEmbedUnimplementedPriceServer() {}

// UnsafePriceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceServer will
// result in compilation errors.
type UnsafePriceServer interface {
	mustEmbedUnimplementedPriceServer()
}

func RegisterPriceServer(s grpc.ServiceRegistrar, srv PriceServer) {
	s.RegisterService(&Price_ServiceDesc, srv)
}

func _Price_EstimatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).EstimatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_EstimatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).EstimatePrice(ctx, req.(*EstimatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Price_CalculateDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).CalculateDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_CalculateDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).CalculateDiscount(ctx, req.(*CalculateDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Price_SaveActualOrderPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveActualOrderPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).SaveActualOrderPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_SaveActualOrderPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).SaveActualOrderPrice(ctx, req.(*SaveActualOrderPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Price_GetOrderPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).GetOrderPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_GetOrderPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).GetOrderPrice(ctx, req.(*GetOrderPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Price_ListPriceRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRuleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).ListPriceRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_ListPriceRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).ListPriceRules(ctx, req.(*PriceRuleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Price_GetPriceRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRuleDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).GetPriceRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_GetPriceRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).GetPriceRule(ctx, req.(*PriceRuleDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Price_CreatePriceRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).CreatePriceRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_CreatePriceRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).CreatePriceRule(ctx, req.(*PriceRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Price_UpdatePriceRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).UpdatePriceRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_UpdatePriceRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).UpdatePriceRule(ctx, req.(*PriceRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Price_SetPriceRuleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRuleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).SetPriceRuleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Price_SetPriceRuleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).SetPriceRuleStatus(ctx, req.(*PriceRuleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Price_ServiceDesc is the grpc.ServiceDesc for Price service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Price_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pricesvc.Price",
	HandlerType: (*PriceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstimatePrice",
			Handler:    _Price_EstimatePrice_Handler,
		},
		{
			MethodName: "CalculateDiscount",
			Handler:    _Price_CalculateDiscount_Handler,
		},
		{
			MethodName: "SaveActualOrderPrice",
			Handler:    _Price_SaveActualOrderPrice_Handler,
		},
		{
			MethodName: "GetOrderPrice",
			Handler:    _Price_GetOrderPrice_Handler,
		},
		{
			MethodName: "ListPriceRules",
			Handler:    _Price_ListPriceRules_Handler,
		},
		{
			MethodName: "GetPriceRule",
			Handler:    _Price_GetPriceRule_Handler,
		},
		{
			MethodName: "CreatePriceRule",
			Handler:    _Price_CreatePriceRule_Handler,
		},
		{
			MethodName: "UpdatePriceRule",
			Handler:    _Price_UpdatePriceRule_Handler,
		},
		{
			MethodName: "SetPriceRuleStatus",
			Handler:    _Price_SetPriceRuleStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/pricesvc/proto/pricesvc.proto",
}
