// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	driverFieldNames          = builder.RawFieldNames(&Driver{})
	driverRows                = strings.Join(driverFieldNames, ",")
	driverRowsExpectAutoSet   = strings.Join(stringx.Remove(driverFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	driverRowsWithPlaceHolder = strings.Join(stringx.Remove(driverFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	driverModel interface {
		Insert(ctx context.Context, data *Driver) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Driver, error)
		FindOneByDriverLicenseNo(ctx context.Context, driverLicenseNo string) (*Driver, error)
		FindOneByPhone(ctx context.Context, phone string) (*Driver, error)
		Update(ctx context.Context, data *Driver) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDriverModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Driver struct {
		Id              int64        `db:"id"`                // 司机ID
		Phone           string       `db:"phone"`             // 手机号（登录账号）
		PasswordHash    string       `db:"password_hash"`     // 密码哈希
		RealName        string       `db:"real_name"`         // 真实姓名
		IdCardNo        string       `db:"id_card_no"`        // 身份证号
		DriverLicenseNo string       `db:"driver_license_no"` // 驾驶证号
		AvatarUrl       string       `db:"avatar_url"`        // 头像地址
		Status          int64        `db:"status"`            // 账号状态：1待审核 2正常 3冻结 4注销
		CreatedAt       time.Time    `db:"created_at"`        // 创建时间
		UpdatedAt       time.Time    `db:"updated_at"`        // 更新时间
		DeletedAt       sql.NullTime `db:"deleted_at"`        // 软删除时间
	}
)

func newDriverModel(conn sqlx.SqlConn) *defaultDriverModel {
	return &defaultDriverModel{
		conn:  conn,
		table: "`driver`",
	}
}

func (m *defaultDriverModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDriverModel) FindOne(ctx context.Context, id int64) (*Driver, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", driverRows, m.table)
	var resp Driver
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDriverModel) FindOneByDriverLicenseNo(ctx context.Context, driverLicenseNo string) (*Driver, error) {
	var resp Driver
	query := fmt.Sprintf("select %s from %s where `driver_license_no` = ? limit 1", driverRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, driverLicenseNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDriverModel) FindOneByPhone(ctx context.Context, phone string) (*Driver, error) {
	var resp Driver
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", driverRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDriverModel) Insert(ctx context.Context, data *Driver) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, driverRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.PasswordHash, data.RealName, data.IdCardNo, data.DriverLicenseNo, data.AvatarUrl, data.Status, data.DeletedAt)
	return ret, err
}

func (m *defaultDriverModel) Update(ctx context.Context, newData *Driver) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, driverRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Phone, newData.PasswordHash, newData.RealName, newData.IdCardNo, newData.DriverLicenseNo, newData.AvatarUrl, newData.Status, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultDriverModel) tableName() string {
	return m.table
}
