// Code generated by goctl. DO NOT EDIT.
// Source: driversvc.proto

package driversvc

import (
	"context"

	"XiaoLong-Ridy/rpc/driversvc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuditCertificationRequest = __proto.AuditCertificationRequest
	CommonResponse            = __proto.CommonResponse
	CreateDriverRequest       = __proto.CreateDriverRequest
	CreateDriverResponse      = __proto.CreateDriverResponse
	CreateVehicleRequest      = __proto.CreateVehicleRequest
	CreateVehicleResponse     = __proto.CreateVehicleResponse
	DeleteDriverRequest       = __proto.DeleteDriverRequest
	DeleteDriverResponse      = __proto.DeleteDriverResponse
	DeleteVehicleRequest      = __proto.DeleteVehicleRequest
	DeleteVehicleResponse     = __proto.DeleteVehicleResponse
	Driver                    = __proto.Driver
	GetDriverRequest          = __proto.GetDriverRequest
	GetDriverResponse         = __proto.GetDriverResponse
	GetVehicleRequest         = __proto.GetVehicleRequest
	GetVehicleResponse        = __proto.GetVehicleResponse
	ListDriversRequest        = __proto.ListDriversRequest
	ListDriversResponse       = __proto.ListDriversResponse
	UpdateDriverRequest       = __proto.UpdateDriverRequest
	UpdateDriverResponse      = __proto.UpdateDriverResponse
	UpdateVehicleRequest      = __proto.UpdateVehicleRequest
	UpdateVehicleResponse     = __proto.UpdateVehicleResponse
	Vehicle                   = __proto.Vehicle

	Driversvc interface {
		// 司机主表 CRUD（仅司机增删改查）
		CreateDriver(ctx context.Context, in *CreateDriverRequest, opts ...grpc.CallOption) (*CreateDriverResponse, error)
		UpdateDriver(ctx context.Context, in *UpdateDriverRequest, opts ...grpc.CallOption) (*UpdateDriverResponse, error)
		DeleteDriver(ctx context.Context, in *DeleteDriverRequest, opts ...grpc.CallOption) (*DeleteDriverResponse, error)
		GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*GetDriverResponse, error)
		// 分页查询司机基础资料，供管理后台只读展示。
		ListDrivers(ctx context.Context, in *ListDriversRequest, opts ...grpc.CallOption) (*ListDriversResponse, error)
		// 车辆 CRUD（司机绑定车辆增删改查）
		CreateVehicle(ctx context.Context, in *CreateVehicleRequest, opts ...grpc.CallOption) (*CreateVehicleResponse, error)
		UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...grpc.CallOption) (*UpdateVehicleResponse, error)
		DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...grpc.CallOption) (*DeleteVehicleResponse, error)
		GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...grpc.CallOption) (*GetVehicleResponse, error)
		// 审核通过司机资质。
		ApproveCertification(ctx context.Context, in *AuditCertificationRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 审核驳回司机资质。
		RejectCertification(ctx context.Context, in *AuditCertificationRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	}

	defaultDriversvc struct {
		cli zrpc.Client
	}
)

func NewDriversvc(cli zrpc.Client) Driversvc {
	return &defaultDriversvc{
		cli: cli,
	}
}

// 司机主表 CRUD（仅司机增删改查）
func (m *defaultDriversvc) CreateDriver(ctx context.Context, in *CreateDriverRequest, opts ...grpc.CallOption) (*CreateDriverResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.CreateDriver(ctx, in, opts...)
}

func (m *defaultDriversvc) UpdateDriver(ctx context.Context, in *UpdateDriverRequest, opts ...grpc.CallOption) (*UpdateDriverResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.UpdateDriver(ctx, in, opts...)
}

func (m *defaultDriversvc) DeleteDriver(ctx context.Context, in *DeleteDriverRequest, opts ...grpc.CallOption) (*DeleteDriverResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.DeleteDriver(ctx, in, opts...)
}

func (m *defaultDriversvc) GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*GetDriverResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.GetDriver(ctx, in, opts...)
}

// 分页查询司机基础资料，供管理后台只读展示。
func (m *defaultDriversvc) ListDrivers(ctx context.Context, in *ListDriversRequest, opts ...grpc.CallOption) (*ListDriversResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.ListDrivers(ctx, in, opts...)
}

// 车辆 CRUD（司机绑定车辆增删改查）
func (m *defaultDriversvc) CreateVehicle(ctx context.Context, in *CreateVehicleRequest, opts ...grpc.CallOption) (*CreateVehicleResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.CreateVehicle(ctx, in, opts...)
}

func (m *defaultDriversvc) UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...grpc.CallOption) (*UpdateVehicleResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.UpdateVehicle(ctx, in, opts...)
}

func (m *defaultDriversvc) DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...grpc.CallOption) (*DeleteVehicleResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.DeleteVehicle(ctx, in, opts...)
}

func (m *defaultDriversvc) GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...grpc.CallOption) (*GetVehicleResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.GetVehicle(ctx, in, opts...)
}

// 审核通过司机资质。
func (m *defaultDriversvc) ApproveCertification(ctx context.Context, in *AuditCertificationRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.ApproveCertification(ctx, in, opts...)
}

// 审核驳回司机资质。
func (m *defaultDriversvc) RejectCertification(ctx context.Context, in *AuditCertificationRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := __proto.NewDriversvcClient(m.cli.Conn())
	return client.RejectCertification(ctx, in, opts...)
}
