// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: proto/driversvc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DriverStatus 司机账号状态枚举。
type DriverStatus int32

const (
	DriverStatus_DRIVER_STATUS_UNSPECIFIED DriverStatus = 0
	DriverStatus_DRIVER_STATUS_PENDING     DriverStatus = 1
	DriverStatus_DRIVER_STATUS_NORMAL      DriverStatus = 2
	DriverStatus_DRIVER_STATUS_FROZEN      DriverStatus = 3
	DriverStatus_DRIVER_STATUS_CANCELLED   DriverStatus = 4
)

// Enum value maps for DriverStatus.
var (
	DriverStatus_name = map[int32]string{
		0: "DRIVER_STATUS_UNSPECIFIED",
		1: "DRIVER_STATUS_PENDING",
		2: "DRIVER_STATUS_NORMAL",
		3: "DRIVER_STATUS_FROZEN",
		4: "DRIVER_STATUS_CANCELLED",
	}
	DriverStatus_value = map[string]int32{
		"DRIVER_STATUS_UNSPECIFIED": 0,
		"DRIVER_STATUS_PENDING":     1,
		"DRIVER_STATUS_NORMAL":      2,
		"DRIVER_STATUS_FROZEN":      3,
		"DRIVER_STATUS_CANCELLED":   4,
	}
)

func (x DriverStatus) Enum() *DriverStatus {
	p := new(DriverStatus)
	*p = x
	return p
}

func (x DriverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_driversvc_proto_enumTypes[0].Descriptor()
}

func (DriverStatus) Type() protoreflect.EnumType {
	return &file_proto_driversvc_proto_enumTypes[0]
}

func (x DriverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatus.Descriptor instead.
func (DriverStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{0}
}

// VehicleStatus 车辆状态枚举，对齐 driver_vehicle.status 字段。
type VehicleStatus int32

const (
	VehicleStatus_VEHICLE_STATUS_UNSPECIFIED VehicleStatus = 0
	VehicleStatus_VEHICLE_STATUS_PENDING     VehicleStatus = 1
	VehicleStatus_VEHICLE_STATUS_NORMAL      VehicleStatus = 2
	VehicleStatus_VEHICLE_STATUS_DISABLED    VehicleStatus = 3
)

// Enum value maps for VehicleStatus.
var (
	VehicleStatus_name = map[int32]string{
		0: "VEHICLE_STATUS_UNSPECIFIED",
		1: "VEHICLE_STATUS_PENDING",
		2: "VEHICLE_STATUS_NORMAL",
		3: "VEHICLE_STATUS_DISABLED",
	}
	VehicleStatus_value = map[string]int32{
		"VEHICLE_STATUS_UNSPECIFIED": 0,
		"VEHICLE_STATUS_PENDING":     1,
		"VEHICLE_STATUS_NORMAL":      2,
		"VEHICLE_STATUS_DISABLED":    3,
	}
)

func (x VehicleStatus) Enum() *VehicleStatus {
	p := new(VehicleStatus)
	*p = x
	return p
}

func (x VehicleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_driversvc_proto_enumTypes[1].Descriptor()
}

func (VehicleStatus) Type() protoreflect.EnumType {
	return &file_proto_driversvc_proto_enumTypes[1]
}

func (x VehicleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatus.Descriptor instead.
func (VehicleStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{1}
}

// Driver 司机信息，对应 driver 表的完整记录。
type Driver struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone           string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	PasswordHash    string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	RealName        string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCardNo        string                 `protobuf:"bytes,5,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	DriverLicenseNo string                 `protobuf:"bytes,6,opt,name=driver_license_no,json=driverLicenseNo,proto3" json:"driver_license_no,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Status          DriverStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=driversvc.DriverStatus" json:"status,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OnlineStatus    int32                  `protobuf:"varint,11,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_proto_driversvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{0}
}

func (x *Driver) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Driver) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Driver) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *Driver) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *Driver) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

func (x *Driver) GetDriverLicenseNo() string {
	if x != nil {
		return x.DriverLicenseNo
	}
	return ""
}

func (x *Driver) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Driver) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_DRIVER_STATUS_UNSPECIFIED
}

func (x *Driver) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Driver) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Driver) GetOnlineStatus() int32 {
	if x != nil {
		return x.OnlineStatus
	}
	return 0
}

type CreateDriverRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Phone           string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	PasswordHash    string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	RealName        string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCardNo        string                 `protobuf:"bytes,4,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	DriverLicenseNo string                 `protobuf:"bytes,5,opt,name=driver_license_no,json=driverLicenseNo,proto3" json:"driver_license_no,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDriverRequest) Reset() {
	*x = CreateDriverRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverRequest) ProtoMessage() {}

func (x *CreateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateDriverRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *CreateDriverRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *CreateDriverRequest) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

func (x *CreateDriverRequest) GetDriverLicenseNo() string {
	if x != nil {
		return x.DriverLicenseNo
	}
	return ""
}

func (x *CreateDriverRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type CreateDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        DriverStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=driversvc.DriverStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverResponse) Reset() {
	*x = CreateDriverResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverResponse) ProtoMessage() {}

func (x *CreateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverResponse.ProtoReflect.Descriptor instead.
func (*CreateDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDriverResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateDriverResponse) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_DRIVER_STATUS_UNSPECIFIED
}

func (x *CreateDriverResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UpdateDriverRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone           *string                `protobuf:"bytes,2,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	PasswordHash    *string                `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3,oneof" json:"password_hash,omitempty"`
	RealName        *string                `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3,oneof" json:"real_name,omitempty"`
	IdCardNo        *string                `protobuf:"bytes,5,opt,name=id_card_no,json=idCardNo,proto3,oneof" json:"id_card_no,omitempty"`
	DriverLicenseNo *string                `protobuf:"bytes,6,opt,name=driver_license_no,json=driverLicenseNo,proto3,oneof" json:"driver_license_no,omitempty"`
	AvatarUrl       *string                `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Status          *DriverStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=driversvc.DriverStatus,oneof" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateDriverRequest) Reset() {
	*x = UpdateDriverRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverRequest) ProtoMessage() {}

func (x *UpdateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDriverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateDriverRequest) GetPasswordHash() string {
	if x != nil && x.PasswordHash != nil {
		return *x.PasswordHash
	}
	return ""
}

func (x *UpdateDriverRequest) GetRealName() string {
	if x != nil && x.RealName != nil {
		return *x.RealName
	}
	return ""
}

func (x *UpdateDriverRequest) GetIdCardNo() string {
	if x != nil && x.IdCardNo != nil {
		return *x.IdCardNo
	}
	return ""
}

func (x *UpdateDriverRequest) GetDriverLicenseNo() string {
	if x != nil && x.DriverLicenseNo != nil {
		return *x.DriverLicenseNo
	}
	return ""
}

func (x *UpdateDriverRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateDriverRequest) GetStatus() DriverStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DriverStatus_DRIVER_STATUS_UNSPECIFIED
}

type UpdateDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        DriverStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=driversvc.DriverStatus" json:"status,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverResponse) Reset() {
	*x = UpdateDriverResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverResponse) ProtoMessage() {}

func (x *UpdateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDriverResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverResponse) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_DRIVER_STATUS_UNSPECIFIED
}

func (x *UpdateDriverResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type DeleteDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverRequest) Reset() {
	*x = DeleteDriverRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverRequest) ProtoMessage() {}

func (x *DeleteDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverRequest.ProtoReflect.Descriptor instead.
func (*DeleteDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDriverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverResponse) Reset() {
	*x = DeleteDriverResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverResponse) ProtoMessage() {}

func (x *DeleteDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverResponse.ProtoReflect.Descriptor instead.
func (*DeleteDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDriverResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteDriverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverRequest) Reset() {
	*x = GetDriverRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverRequest) ProtoMessage() {}

func (x *GetDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverRequest.ProtoReflect.Descriptor instead.
func (*GetDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{7}
}

func (x *GetDriverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        *Driver                `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverResponse) Reset() {
	*x = GetDriverResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverResponse) ProtoMessage() {}

func (x *GetDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverResponse.ProtoReflect.Descriptor instead.
func (*GetDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{8}
}

func (x *GetDriverResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

type SetDriverOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriverOnlineRequest) Reset() {
	*x = SetDriverOnlineRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriverOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriverOnlineRequest) ProtoMessage() {}

func (x *SetDriverOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriverOnlineRequest.ProtoReflect.Descriptor instead.
func (*SetDriverOnlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{9}
}

func (x *SetDriverOnlineRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type SetDriverOnlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OnlineStatus  int32                  `protobuf:"varint,2,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriverOnlineResponse) Reset() {
	*x = SetDriverOnlineResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriverOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriverOnlineResponse) ProtoMessage() {}

func (x *SetDriverOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriverOnlineResponse.ProtoReflect.Descriptor instead.
func (*SetDriverOnlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{10}
}

func (x *SetDriverOnlineResponse) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *SetDriverOnlineResponse) GetOnlineStatus() int32 {
	if x != nil {
		return x.OnlineStatus
	}
	return 0
}

type SetDriverOfflineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriverOfflineRequest) Reset() {
	*x = SetDriverOfflineRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriverOfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriverOfflineRequest) ProtoMessage() {}

func (x *SetDriverOfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriverOfflineRequest.ProtoReflect.Descriptor instead.
func (*SetDriverOfflineRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{11}
}

func (x *SetDriverOfflineRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type SetDriverOfflineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OnlineStatus  int32                  `protobuf:"varint,2,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriverOfflineResponse) Reset() {
	*x = SetDriverOfflineResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriverOfflineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriverOfflineResponse) ProtoMessage() {}

func (x *SetDriverOfflineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriverOfflineResponse.ProtoReflect.Descriptor instead.
func (*SetDriverOfflineResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{12}
}

func (x *SetDriverOfflineResponse) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *SetDriverOfflineResponse) GetOnlineStatus() int32 {
	if x != nil {
		return x.OnlineStatus
	}
	return 0
}

type GetDriverByPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverByPhoneRequest) Reset() {
	*x = GetDriverByPhoneRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverByPhoneRequest) ProtoMessage() {}

func (x *GetDriverByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverByPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetDriverByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{13}
}

func (x *GetDriverByPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetDriverByPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        *Driver                `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverByPhoneResponse) Reset() {
	*x = GetDriverByPhoneResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverByPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverByPhoneResponse) ProtoMessage() {}

func (x *GetDriverByPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverByPhoneResponse.ProtoReflect.Descriptor instead.
func (*GetDriverByPhoneResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{14}
}

func (x *GetDriverByPhoneResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

// Vehicle 车辆信息，对应 driver_vehicle 表的完整记录。
type Vehicle struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId          int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	PlateNo           string                 `protobuf:"bytes,3,opt,name=plate_no,json=plateNo,proto3" json:"plate_no,omitempty"`
	Brand             string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Model             string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Color             string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	VehicleType       int32                  `protobuf:"varint,7,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	RegistrationDate  *int64                 `protobuf:"varint,8,opt,name=registration_date,json=registrationDate,proto3,oneof" json:"registration_date,omitempty"`
	InsuranceNo       string                 `protobuf:"bytes,9,opt,name=insurance_no,json=insuranceNo,proto3" json:"insurance_no,omitempty"`
	InsuranceExpireAt *int64                 `protobuf:"varint,10,opt,name=insurance_expire_at,json=insuranceExpireAt,proto3,oneof" json:"insurance_expire_at,omitempty"`
	Status            VehicleStatus          `protobuf:"varint,11,opt,name=status,proto3,enum=driversvc.VehicleStatus" json:"status,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_proto_driversvc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{15}
}

func (x *Vehicle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vehicle) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *Vehicle) GetPlateNo() string {
	if x != nil {
		return x.PlateNo
	}
	return ""
}

func (x *Vehicle) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Vehicle) GetVehicleType() int32 {
	if x != nil {
		return x.VehicleType
	}
	return 0
}

func (x *Vehicle) GetRegistrationDate() int64 {
	if x != nil && x.RegistrationDate != nil {
		return *x.RegistrationDate
	}
	return 0
}

func (x *Vehicle) GetInsuranceNo() string {
	if x != nil {
		return x.InsuranceNo
	}
	return ""
}

func (x *Vehicle) GetInsuranceExpireAt() int64 {
	if x != nil && x.InsuranceExpireAt != nil {
		return *x.InsuranceExpireAt
	}
	return 0
}

func (x *Vehicle) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_VEHICLE_STATUS_UNSPECIFIED
}

func (x *Vehicle) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Vehicle) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateVehicleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DriverId          int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	PlateNo           string                 `protobuf:"bytes,2,opt,name=plate_no,json=plateNo,proto3" json:"plate_no,omitempty"`
	Brand             string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model             string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Color             string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	VehicleType       int32                  `protobuf:"varint,6,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	RegistrationDate  *int64                 `protobuf:"varint,7,opt,name=registration_date,json=registrationDate,proto3,oneof" json:"registration_date,omitempty"`
	InsuranceNo       string                 `protobuf:"bytes,8,opt,name=insurance_no,json=insuranceNo,proto3" json:"insurance_no,omitempty"`
	InsuranceExpireAt *int64                 `protobuf:"varint,9,opt,name=insurance_expire_at,json=insuranceExpireAt,proto3,oneof" json:"insurance_expire_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{16}
}

func (x *CreateVehicleRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *CreateVehicleRequest) GetPlateNo() string {
	if x != nil {
		return x.PlateNo
	}
	return ""
}

func (x *CreateVehicleRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateVehicleRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateVehicleRequest) GetVehicleType() int32 {
	if x != nil {
		return x.VehicleType
	}
	return 0
}

func (x *CreateVehicleRequest) GetRegistrationDate() int64 {
	if x != nil && x.RegistrationDate != nil {
		return *x.RegistrationDate
	}
	return 0
}

func (x *CreateVehicleRequest) GetInsuranceNo() string {
	if x != nil {
		return x.InsuranceNo
	}
	return ""
}

func (x *CreateVehicleRequest) GetInsuranceExpireAt() int64 {
	if x != nil && x.InsuranceExpireAt != nil {
		return *x.InsuranceExpireAt
	}
	return 0
}

type CreateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        VehicleStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=driversvc.VehicleStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleResponse) Reset() {
	*x = CreateVehicleResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleResponse) ProtoMessage() {}

func (x *CreateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleResponse.ProtoReflect.Descriptor instead.
func (*CreateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{17}
}

func (x *CreateVehicleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateVehicleResponse) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_VEHICLE_STATUS_UNSPECIFIED
}

func (x *CreateVehicleResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UpdateVehicleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId          *int64                 `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3,oneof" json:"driver_id,omitempty"`
	PlateNo           *string                `protobuf:"bytes,3,opt,name=plate_no,json=plateNo,proto3,oneof" json:"plate_no,omitempty"`
	Brand             *string                `protobuf:"bytes,4,opt,name=brand,proto3,oneof" json:"brand,omitempty"`
	Model             *string                `protobuf:"bytes,5,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Color             *string                `protobuf:"bytes,6,opt,name=color,proto3,oneof" json:"color,omitempty"`
	VehicleType       *int32                 `protobuf:"varint,7,opt,name=vehicle_type,json=vehicleType,proto3,oneof" json:"vehicle_type,omitempty"`
	RegistrationDate  *int64                 `protobuf:"varint,8,opt,name=registration_date,json=registrationDate,proto3,oneof" json:"registration_date,omitempty"`
	InsuranceNo       *string                `protobuf:"bytes,9,opt,name=insurance_no,json=insuranceNo,proto3,oneof" json:"insurance_no,omitempty"`
	InsuranceExpireAt *int64                 `protobuf:"varint,10,opt,name=insurance_expire_at,json=insuranceExpireAt,proto3,oneof" json:"insurance_expire_at,omitempty"`
	Status            *VehicleStatus         `protobuf:"varint,11,opt,name=status,proto3,enum=driversvc.VehicleStatus,oneof" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateVehicleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVehicleRequest) GetDriverId() int64 {
	if x != nil && x.DriverId != nil {
		return *x.DriverId
	}
	return 0
}

func (x *UpdateVehicleRequest) GetPlateNo() string {
	if x != nil && x.PlateNo != nil {
		return *x.PlateNo
	}
	return ""
}

func (x *UpdateVehicleRequest) GetBrand() string {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return ""
}

func (x *UpdateVehicleRequest) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *UpdateVehicleRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateVehicleRequest) GetVehicleType() int32 {
	if x != nil && x.VehicleType != nil {
		return *x.VehicleType
	}
	return 0
}

func (x *UpdateVehicleRequest) GetRegistrationDate() int64 {
	if x != nil && x.RegistrationDate != nil {
		return *x.RegistrationDate
	}
	return 0
}

func (x *UpdateVehicleRequest) GetInsuranceNo() string {
	if x != nil && x.InsuranceNo != nil {
		return *x.InsuranceNo
	}
	return ""
}

func (x *UpdateVehicleRequest) GetInsuranceExpireAt() int64 {
	if x != nil && x.InsuranceExpireAt != nil {
		return *x.InsuranceExpireAt
	}
	return 0
}

func (x *UpdateVehicleRequest) GetStatus() VehicleStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return VehicleStatus_VEHICLE_STATUS_UNSPECIFIED
}

type UpdateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        VehicleStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=driversvc.VehicleStatus" json:"status,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleResponse) Reset() {
	*x = UpdateVehicleResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleResponse) ProtoMessage() {}

func (x *UpdateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleResponse.ProtoReflect.Descriptor instead.
func (*UpdateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateVehicleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVehicleResponse) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_VEHICLE_STATUS_UNSPECIFIED
}

func (x *UpdateVehicleResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type DeleteVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteVehicleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleResponse) Reset() {
	*x = DeleteVehicleResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleResponse) ProtoMessage() {}

func (x *DeleteVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleResponse.ProtoReflect.Descriptor instead.
func (*DeleteVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteVehicleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteVehicleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{22}
}

func (x *GetVehicleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{23}
}

func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

// ListDriversRequest 司机列表查询请求。
type ListDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                       // 页码，从 1 开始，缺省为 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`               // 每页条数，缺省为 20
	Status        *DriverStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=driversvc.DriverStatus,oneof" json:"status,omitempty"` // 可选状态过滤
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`                                  // 可选关键字：模糊匹配手机号/姓名/车牌号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriversRequest) Reset() {
	*x = ListDriversRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriversRequest) ProtoMessage() {}

func (x *ListDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriversRequest.ProtoReflect.Descriptor instead.
func (*ListDriversRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{24}
}

func (x *ListDriversRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDriversRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDriversRequest) GetStatus() DriverStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DriverStatus_DRIVER_STATUS_UNSPECIFIED
}

func (x *ListDriversRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// ListDriversResponse 司机列表查询响应。
type ListDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*Driver              `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"` // 当前页司机列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`    // 符合条件的总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriversResponse) Reset() {
	*x = ListDriversResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriversResponse) ProtoMessage() {}

func (x *ListDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriversResponse.ProtoReflect.Descriptor instead.
func (*ListDriversResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{25}
}

func (x *ListDriversResponse) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *ListDriversResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// LoginRequest 司机登录请求。
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`       // 手机号
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 明文密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{26}
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse 司机登录响应。
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                        // 登录凭证 JWT
	ExpireIn      int64                  `protobuf:"varint,2,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"` // 有效期（秒）
	Driver        *Driver                `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`                      // 司机简要信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{27}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpireIn() int64 {
	if x != nil {
		return x.ExpireIn
	}
	return 0
}

func (x *LoginResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

// NearbyDriver 附近司机摘要信息。
type NearbyDriver struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverId       int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`                   // 司机 ID
	Longitude      float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`                                // 经度
	Latitude       float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`                                  // 纬度
	DistanceMeters int32                  `protobuf:"varint,4,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"` // 距查询中心点的距离（米）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NearbyDriver) Reset() {
	*x = NearbyDriver{}
	mi := &file_proto_driversvc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriver) ProtoMessage() {}

func (x *NearbyDriver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriver.ProtoReflect.Descriptor instead.
func (*NearbyDriver) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{28}
}

func (x *NearbyDriver) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *NearbyDriver) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyDriver) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyDriver) GetDistanceMeters() int32 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

// ListNearbyDriversRequest 附近司机查询请求。
type ListNearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`                           // 查询中心经度
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`                             // 查询中心纬度
	RadiusMeters  float64                `protobuf:"fixed64,3,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"` // 搜索半径（米），缺省 3000
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                    // 返回条数上限，缺省 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyDriversRequest) Reset() {
	*x = ListNearbyDriversRequest{}
	mi := &file_proto_driversvc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyDriversRequest) ProtoMessage() {}

func (x *ListNearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*ListNearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{29}
}

func (x *ListNearbyDriversRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ListNearbyDriversRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ListNearbyDriversRequest) GetRadiusMeters() float64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

func (x *ListNearbyDriversRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListNearbyDriversResponse 附近司机查询响应。
type ListNearbyDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*NearbyDriver        `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"` // 附近在线司机列表（按距离升序）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyDriversResponse) Reset() {
	*x = ListNearbyDriversResponse{}
	mi := &file_proto_driversvc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyDriversResponse) ProtoMessage() {}

func (x *ListNearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driversvc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*ListNearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_proto_driversvc_proto_rawDescGZIP(), []int{30}
}

func (x *ListNearbyDriversResponse) GetDrivers() []*NearbyDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

var File_proto_driversvc_proto protoreflect.FileDescriptor

const file_proto_driversvc_proto_rawDesc = "" +
	"\n" +
	"\x15proto/driversvc.proto\x12\tdriversvc\"\xed\x02\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x1c\n" +
	"\n" +
	"id_card_no\x18\x05 \x01(\tR\bidCardNo\x12*\n" +
	"\x11driver_license_no\x18\x06 \x01(\tR\x0fdriverLicenseNo\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12/\n" +
	"\x06status\x18\b \x01(\x0e2\x17.driversvc.DriverStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12#\n" +
	"\ronline_status\x18\v \x01(\x05R\fonlineStatus\"\xd6\x01\n" +
	"\x13CreateDriverRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1c\n" +
	"\n" +
	"id_card_no\x18\x04 \x01(\tR\bidCardNo\x12*\n" +
	"\x11driver_license_no\x18\x05 \x01(\tR\x0fdriverLicenseNo\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\"v\n" +
	"\x14CreateDriverResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.driversvc.DriverStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\xa3\x03\n" +
	"\x13UpdateDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x05phone\x18\x02 \x01(\tH\x00R\x05phone\x88\x01\x01\x12(\n" +
	"\rpassword_hash\x18\x03 \x01(\tH\x01R\fpasswordHash\x88\x01\x01\x12 \n" +
	"\treal_name\x18\x04 \x01(\tH\x02R\brealName\x88\x01\x01\x12!\n" +
	"\n" +
	"id_card_no\x18\x05 \x01(\tH\x03R\bidCardNo\x88\x01\x01\x12/\n" +
	"\x11driver_license_no\x18\x06 \x01(\tH\x04R\x0fdriverLicenseNo\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tH\x05R\tavatarUrl\x88\x01\x01\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x17.driversvc.DriverStatusH\x06R\x06status\x88\x01\x01B\b\n" +
	"\x06_phoneB\x10\n" +
	"\x0e_password_hashB\f\n" +
	"\n" +
	"_real_nameB\r\n" +
	"\v_id_card_noB\x14\n" +
	"\x12_driver_license_noB\r\n" +
	"\v_avatar_urlB\t\n" +
	"\a_status\"v\n" +
	"\x14UpdateDriverResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.driversvc.DriverStatusR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"%\n" +
	"\x13DeleteDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x14DeleteDriverResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\"\n" +
	"\x10GetDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x11GetDriverResponse\x12)\n" +
	"\x06driver\x18\x01 \x01(\v2\x11.driversvc.DriverR\x06driver\"5\n" +
	"\x16SetDriverOnlineRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\"[\n" +
	"\x17SetDriverOnlineResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12#\n" +
	"\ronline_status\x18\x02 \x01(\x05R\fonlineStatus\"6\n" +
	"\x17SetDriverOfflineRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\"\\\n" +
	"\x18SetDriverOfflineResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12#\n" +
	"\ronline_status\x18\x02 \x01(\x05R\fonlineStatus\"/\n" +
	"\x17GetDriverByPhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"E\n" +
	"\x18GetDriverByPhoneResponse\x12)\n" +
	"\x06driver\x18\x01 \x01(\v2\x11.driversvc.DriverR\x06driver\"\xde\x03\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12\x19\n" +
	"\bplate_no\x18\x03 \x01(\tR\aplateNo\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12!\n" +
	"\fvehicle_type\x18\a \x01(\x05R\vvehicleType\x120\n" +
	"\x11registration_date\x18\b \x01(\x03H\x00R\x10registrationDate\x88\x01\x01\x12!\n" +
	"\finsurance_no\x18\t \x01(\tR\vinsuranceNo\x123\n" +
	"\x13insurance_expire_at\x18\n" +
	" \x01(\x03H\x01R\x11insuranceExpireAt\x88\x01\x01\x120\n" +
	"\x06status\x18\v \x01(\x0e2\x18.driversvc.VehicleStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAtB\x14\n" +
	"\x12_registration_dateB\x16\n" +
	"\x14_insurance_expire_at\"\xeb\x02\n" +
	"\x14CreateVehicleRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x19\n" +
	"\bplate_no\x18\x02 \x01(\tR\aplateNo\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12!\n" +
	"\fvehicle_type\x18\x06 \x01(\x05R\vvehicleType\x120\n" +
	"\x11registration_date\x18\a \x01(\x03H\x00R\x10registrationDate\x88\x01\x01\x12!\n" +
	"\finsurance_no\x18\b \x01(\tR\vinsuranceNo\x123\n" +
	"\x13insurance_expire_at\x18\t \x01(\x03H\x01R\x11insuranceExpireAt\x88\x01\x01B\x14\n" +
	"\x12_registration_dateB\x16\n" +
	"\x14_insurance_expire_at\"x\n" +
	"\x15CreateVehicleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.driversvc.VehicleStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\xbb\x04\n" +
	"\x14UpdateVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\tdriver_id\x18\x02 \x01(\x03H\x00R\bdriverId\x88\x01\x01\x12\x1e\n" +
	"\bplate_no\x18\x03 \x01(\tH\x01R\aplateNo\x88\x01\x01\x12\x19\n" +
	"\x05brand\x18\x04 \x01(\tH\x02R\x05brand\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x05 \x01(\tH\x03R\x05model\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x06 \x01(\tH\x04R\x05color\x88\x01\x01\x12&\n" +
	"\fvehicle_type\x18\a \x01(\x05H\x05R\vvehicleType\x88\x01\x01\x120\n" +
	"\x11registration_date\x18\b \x01(\x03H\x06R\x10registrationDate\x88\x01\x01\x12&\n" +
	"\finsurance_no\x18\t \x01(\tH\aR\vinsuranceNo\x88\x01\x01\x123\n" +
	"\x13insurance_expire_at\x18\n" +
	" \x01(\x03H\bR\x11insuranceExpireAt\x88\x01\x01\x125\n" +
	"\x06status\x18\v \x01(\x0e2\x18.driversvc.VehicleStatusH\tR\x06status\x88\x01\x01B\f\n" +
	"\n" +
	"_driver_idB\v\n" +
	"\t_plate_noB\b\n" +
	"\x06_brandB\b\n" +
	"\x06_modelB\b\n" +
	"\x06_colorB\x0f\n" +
	"\r_vehicle_typeB\x14\n" +
	"\x12_registration_dateB\x0f\n" +
	"\r_insurance_noB\x16\n" +
	"\x14_insurance_expire_atB\t\n" +
	"\a_status\"x\n" +
	"\x15UpdateVehicleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.driversvc.VehicleStatusR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"&\n" +
	"\x14DeleteVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x15DeleteVehicleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"#\n" +
	"\x11GetVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\x12GetVehicleResponse\x12,\n" +
	"\avehicle\x18\x01 \x01(\v2\x12.driversvc.VehicleR\avehicle\"\xa0\x01\n" +
	"\x12ListDriversRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.driversvc.DriverStatusH\x00R\x06status\x88\x01\x01\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeywordB\t\n" +
	"\a_status\"X\n" +
	"\x13ListDriversResponse\x12+\n" +
	"\adrivers\x18\x01 \x03(\v2\x11.driversvc.DriverR\adrivers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"m\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\texpire_in\x18\x02 \x01(\x03R\bexpireIn\x12)\n" +
	"\x06driver\x18\x03 \x01(\v2\x11.driversvc.DriverR\x06driver\"\x8e\x01\n" +
	"\fNearbyDriver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12'\n" +
	"\x0fdistance_meters\x18\x04 \x01(\x05R\x0edistanceMeters\"\x8f\x01\n" +
	"\x18ListNearbyDriversRequest\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12#\n" +
	"\rradius_meters\x18\x03 \x01(\x01R\fradiusMeters\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"N\n" +
	"\x19ListNearbyDriversResponse\x121\n" +
	"\adrivers\x18\x01 \x03(\v2\x17.driversvc.NearbyDriverR\adrivers*\x99\x01\n" +
	"\fDriverStatus\x12\x1d\n" +
	"\x19DRIVER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DRIVER_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14DRIVER_STATUS_NORMAL\x10\x02\x12\x18\n" +
	"\x14DRIVER_STATUS_FROZEN\x10\x03\x12\x1b\n" +
	"\x17DRIVER_STATUS_CANCELLED\x10\x04*\x83\x01\n" +
	"\rVehicleStatus\x12\x1e\n" +
	"\x1aVEHICLE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VEHICLE_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15VEHICLE_STATUS_NORMAL\x10\x02\x12\x1b\n" +
	"\x17VEHICLE_STATUS_DISABLED\x10\x032\x8b\t\n" +
	"\tDriversvc\x12O\n" +
	"\fCreateDriver\x12\x1e.driversvc.CreateDriverRequest\x1a\x1f.driversvc.CreateDriverResponse\x12O\n" +
	"\fUpdateDriver\x12\x1e.driversvc.UpdateDriverRequest\x1a\x1f.driversvc.UpdateDriverResponse\x12O\n" +
	"\fDeleteDriver\x12\x1e.driversvc.DeleteDriverRequest\x1a\x1f.driversvc.DeleteDriverResponse\x12F\n" +
	"\tGetDriver\x12\x1b.driversvc.GetDriverRequest\x1a\x1c.driversvc.GetDriverResponse\x12[\n" +
	"\x10GetDriverByPhone\x12\".driversvc.GetDriverByPhoneRequest\x1a#.driversvc.GetDriverByPhoneResponse\x12X\n" +
	"\x0fSetDriverOnline\x12!.driversvc.SetDriverOnlineRequest\x1a\".driversvc.SetDriverOnlineResponse\x12[\n" +
	"\x10SetDriverOffline\x12\".driversvc.SetDriverOfflineRequest\x1a#.driversvc.SetDriverOfflineResponse\x12R\n" +
	"\rCreateVehicle\x12\x1f.driversvc.CreateVehicleRequest\x1a .driversvc.CreateVehicleResponse\x12R\n" +
	"\rUpdateVehicle\x12\x1f.driversvc.UpdateVehicleRequest\x1a .driversvc.UpdateVehicleResponse\x12R\n" +
	"\rDeleteVehicle\x12\x1f.driversvc.DeleteVehicleRequest\x1a .driversvc.DeleteVehicleResponse\x12I\n" +
	"\n" +
	"GetVehicle\x12\x1c.driversvc.GetVehicleRequest\x1a\x1d.driversvc.GetVehicleResponse\x12L\n" +
	"\vListDrivers\x12\x1d.driversvc.ListDriversRequest\x1a\x1e.driversvc.ListDriversResponse\x12:\n" +
	"\x05Login\x12\x17.driversvc.LoginRequest\x1a\x18.driversvc.LoginResponse\x12^\n" +
	"\x11ListNearbyDrivers\x12#.driversvc.ListNearbyDriversRequest\x1a$.driversvc.ListNearbyDriversResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_driversvc_proto_rawDescOnce sync.Once
	file_proto_driversvc_proto_rawDescData []byte
)

func file_proto_driversvc_proto_rawDescGZIP() []byte {
	file_proto_driversvc_proto_rawDescOnce.Do(func() {
		file_proto_driversvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driversvc_proto_rawDesc), len(file_proto_driversvc_proto_rawDesc)))
	})
	return file_proto_driversvc_proto_rawDescData
}

var file_proto_driversvc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_driversvc_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_driversvc_proto_goTypes = []any{
	(DriverStatus)(0),                 // 0: driversvc.DriverStatus
	(VehicleStatus)(0),                // 1: driversvc.VehicleStatus
	(*Driver)(nil),                    // 2: driversvc.Driver
	(*CreateDriverRequest)(nil),       // 3: driversvc.CreateDriverRequest
	(*CreateDriverResponse)(nil),      // 4: driversvc.CreateDriverResponse
	(*UpdateDriverRequest)(nil),       // 5: driversvc.UpdateDriverRequest
	(*UpdateDriverResponse)(nil),      // 6: driversvc.UpdateDriverResponse
	(*DeleteDriverRequest)(nil),       // 7: driversvc.DeleteDriverRequest
	(*DeleteDriverResponse)(nil),      // 8: driversvc.DeleteDriverResponse
	(*GetDriverRequest)(nil),          // 9: driversvc.GetDriverRequest
	(*GetDriverResponse)(nil),         // 10: driversvc.GetDriverResponse
	(*SetDriverOnlineRequest)(nil),    // 11: driversvc.SetDriverOnlineRequest
	(*SetDriverOnlineResponse)(nil),   // 12: driversvc.SetDriverOnlineResponse
	(*SetDriverOfflineRequest)(nil),   // 13: driversvc.SetDriverOfflineRequest
	(*SetDriverOfflineResponse)(nil),  // 14: driversvc.SetDriverOfflineResponse
	(*GetDriverByPhoneRequest)(nil),   // 15: driversvc.GetDriverByPhoneRequest
	(*GetDriverByPhoneResponse)(nil),  // 16: driversvc.GetDriverByPhoneResponse
	(*Vehicle)(nil),                   // 17: driversvc.Vehicle
	(*CreateVehicleRequest)(nil),      // 18: driversvc.CreateVehicleRequest
	(*CreateVehicleResponse)(nil),     // 19: driversvc.CreateVehicleResponse
	(*UpdateVehicleRequest)(nil),      // 20: driversvc.UpdateVehicleRequest
	(*UpdateVehicleResponse)(nil),     // 21: driversvc.UpdateVehicleResponse
	(*DeleteVehicleRequest)(nil),      // 22: driversvc.DeleteVehicleRequest
	(*DeleteVehicleResponse)(nil),     // 23: driversvc.DeleteVehicleResponse
	(*GetVehicleRequest)(nil),         // 24: driversvc.GetVehicleRequest
	(*GetVehicleResponse)(nil),        // 25: driversvc.GetVehicleResponse
	(*ListDriversRequest)(nil),        // 26: driversvc.ListDriversRequest
	(*ListDriversResponse)(nil),       // 27: driversvc.ListDriversResponse
	(*LoginRequest)(nil),              // 28: driversvc.LoginRequest
	(*LoginResponse)(nil),             // 29: driversvc.LoginResponse
	(*NearbyDriver)(nil),              // 30: driversvc.NearbyDriver
	(*ListNearbyDriversRequest)(nil),  // 31: driversvc.ListNearbyDriversRequest
	(*ListNearbyDriversResponse)(nil), // 32: driversvc.ListNearbyDriversResponse
}
var file_proto_driversvc_proto_depIdxs = []int32{
	0,  // 0: driversvc.Driver.status:type_name -> driversvc.DriverStatus
	0,  // 1: driversvc.CreateDriverResponse.status:type_name -> driversvc.DriverStatus
	0,  // 2: driversvc.UpdateDriverRequest.status:type_name -> driversvc.DriverStatus
	0,  // 3: driversvc.UpdateDriverResponse.status:type_name -> driversvc.DriverStatus
	2,  // 4: driversvc.GetDriverResponse.driver:type_name -> driversvc.Driver
	2,  // 5: driversvc.GetDriverByPhoneResponse.driver:type_name -> driversvc.Driver
	1,  // 6: driversvc.Vehicle.status:type_name -> driversvc.VehicleStatus
	1,  // 7: driversvc.CreateVehicleResponse.status:type_name -> driversvc.VehicleStatus
	1,  // 8: driversvc.UpdateVehicleRequest.status:type_name -> driversvc.VehicleStatus
	1,  // 9: driversvc.UpdateVehicleResponse.status:type_name -> driversvc.VehicleStatus
	17, // 10: driversvc.GetVehicleResponse.vehicle:type_name -> driversvc.Vehicle
	0,  // 11: driversvc.ListDriversRequest.status:type_name -> driversvc.DriverStatus
	2,  // 12: driversvc.ListDriversResponse.drivers:type_name -> driversvc.Driver
	2,  // 13: driversvc.LoginResponse.driver:type_name -> driversvc.Driver
	30, // 14: driversvc.ListNearbyDriversResponse.drivers:type_name -> driversvc.NearbyDriver
	3,  // 15: driversvc.Driversvc.CreateDriver:input_type -> driversvc.CreateDriverRequest
	5,  // 16: driversvc.Driversvc.UpdateDriver:input_type -> driversvc.UpdateDriverRequest
	7,  // 17: driversvc.Driversvc.DeleteDriver:input_type -> driversvc.DeleteDriverRequest
	9,  // 18: driversvc.Driversvc.GetDriver:input_type -> driversvc.GetDriverRequest
	15, // 19: driversvc.Driversvc.GetDriverByPhone:input_type -> driversvc.GetDriverByPhoneRequest
	11, // 20: driversvc.Driversvc.SetDriverOnline:input_type -> driversvc.SetDriverOnlineRequest
	13, // 21: driversvc.Driversvc.SetDriverOffline:input_type -> driversvc.SetDriverOfflineRequest
	18, // 22: driversvc.Driversvc.CreateVehicle:input_type -> driversvc.CreateVehicleRequest
	20, // 23: driversvc.Driversvc.UpdateVehicle:input_type -> driversvc.UpdateVehicleRequest
	22, // 24: driversvc.Driversvc.DeleteVehicle:input_type -> driversvc.DeleteVehicleRequest
	24, // 25: driversvc.Driversvc.GetVehicle:input_type -> driversvc.GetVehicleRequest
	26, // 26: driversvc.Driversvc.ListDrivers:input_type -> driversvc.ListDriversRequest
	28, // 27: driversvc.Driversvc.Login:input_type -> driversvc.LoginRequest
	31, // 28: driversvc.Driversvc.ListNearbyDrivers:input_type -> driversvc.ListNearbyDriversRequest
	4,  // 29: driversvc.Driversvc.CreateDriver:output_type -> driversvc.CreateDriverResponse
	6,  // 30: driversvc.Driversvc.UpdateDriver:output_type -> driversvc.UpdateDriverResponse
	8,  // 31: driversvc.Driversvc.DeleteDriver:output_type -> driversvc.DeleteDriverResponse
	10, // 32: driversvc.Driversvc.GetDriver:output_type -> driversvc.GetDriverResponse
	16, // 33: driversvc.Driversvc.GetDriverByPhone:output_type -> driversvc.GetDriverByPhoneResponse
	12, // 34: driversvc.Driversvc.SetDriverOnline:output_type -> driversvc.SetDriverOnlineResponse
	14, // 35: driversvc.Driversvc.SetDriverOffline:output_type -> driversvc.SetDriverOfflineResponse
	19, // 36: driversvc.Driversvc.CreateVehicle:output_type -> driversvc.CreateVehicleResponse
	21, // 37: driversvc.Driversvc.UpdateVehicle:output_type -> driversvc.UpdateVehicleResponse
	23, // 38: driversvc.Driversvc.DeleteVehicle:output_type -> driversvc.DeleteVehicleResponse
	25, // 39: driversvc.Driversvc.GetVehicle:output_type -> driversvc.GetVehicleResponse
	27, // 40: driversvc.Driversvc.ListDrivers:output_type -> driversvc.ListDriversResponse
	29, // 41: driversvc.Driversvc.Login:output_type -> driversvc.LoginResponse
	32, // 42: driversvc.Driversvc.ListNearbyDrivers:output_type -> driversvc.ListNearbyDriversResponse
	29, // [29:43] is the sub-list for method output_type
	15, // [15:29] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_driversvc_proto_init() }
func file_proto_driversvc_proto_init() {
	if File_proto_driversvc_proto != nil {
		return
	}
	file_proto_driversvc_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_driversvc_proto_msgTypes[15].OneofWrappers = []any{}
	file_proto_driversvc_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_driversvc_proto_msgTypes[18].OneofWrappers = []any{}
	file_proto_driversvc_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driversvc_proto_rawDesc), len(file_proto_driversvc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driversvc_proto_goTypes,
		DependencyIndexes: file_proto_driversvc_proto_depIdxs,
		EnumInfos:         file_proto_driversvc_proto_enumTypes,
		MessageInfos:      file_proto_driversvc_proto_msgTypes,
	}.Build()
	File_proto_driversvc_proto = out.File
	file_proto_driversvc_proto_goTypes = nil
	file_proto_driversvc_proto_depIdxs = nil
}
