// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: rpc/driversvc/proto/driversvc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Driversvc_Ping_FullMethodName         = "/driversvc.Driversvc/Ping"
	Driversvc_CreateDriver_FullMethodName = "/driversvc.Driversvc/CreateDriver"
	Driversvc_UpdateDriver_FullMethodName = "/driversvc.Driversvc/UpdateDriver"
	Driversvc_DeleteDriver_FullMethodName = "/driversvc.Driversvc/DeleteDriver"
	Driversvc_GetDriver_FullMethodName    = "/driversvc.Driversvc/GetDriver"
	Driversvc_ListDrivers_FullMethodName  = "/driversvc.Driversvc/ListDrivers"
)

// DriversvcClient is the client API for Driversvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriversvcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	CreateDriver(ctx context.Context, in *CreateDriverRequest, opts ...grpc.CallOption) (*CreateDriverResponse, error)
	UpdateDriver(ctx context.Context, in *UpdateDriverRequest, opts ...grpc.CallOption) (*UpdateDriverResponse, error)
	DeleteDriver(ctx context.Context, in *DeleteDriverRequest, opts ...grpc.CallOption) (*DeleteDriverResponse, error)
	GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*GetDriverResponse, error)
	ListDrivers(ctx context.Context, in *ListDriversRequest, opts ...grpc.CallOption) (*ListDriversResponse, error)
}

type driversvcClient struct {
	cc grpc.ClientConnInterface
}

func NewDriversvcClient(cc grpc.ClientConnInterface) DriversvcClient {
	return &driversvcClient{cc}
}

func (c *driversvcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Driversvc_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driversvcClient) CreateDriver(ctx context.Context, in *CreateDriverRequest, opts ...grpc.CallOption) (*CreateDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDriverResponse)
	err := c.cc.Invoke(ctx, Driversvc_CreateDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driversvcClient) UpdateDriver(ctx context.Context, in *UpdateDriverRequest, opts ...grpc.CallOption) (*UpdateDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDriverResponse)
	err := c.cc.Invoke(ctx, Driversvc_UpdateDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driversvcClient) DeleteDriver(ctx context.Context, in *DeleteDriverRequest, opts ...grpc.CallOption) (*DeleteDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDriverResponse)
	err := c.cc.Invoke(ctx, Driversvc_DeleteDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driversvcClient) GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*GetDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverResponse)
	err := c.cc.Invoke(ctx, Driversvc_GetDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driversvcClient) ListDrivers(ctx context.Context, in *ListDriversRequest, opts ...grpc.CallOption) (*ListDriversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriversResponse)
	err := c.cc.Invoke(ctx, Driversvc_ListDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriversvcServer is the server API for Driversvc service.
// All implementations must embed UnimplementedDriversvcServer
// for forward compatibility.
type DriversvcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	CreateDriver(context.Context, *CreateDriverRequest) (*CreateDriverResponse, error)
	UpdateDriver(context.Context, *UpdateDriverRequest) (*UpdateDriverResponse, error)
	DeleteDriver(context.Context, *DeleteDriverRequest) (*DeleteDriverResponse, error)
	GetDriver(context.Context, *GetDriverRequest) (*GetDriverResponse, error)
	ListDrivers(context.Context, *ListDriversRequest) (*ListDriversResponse, error)
	mustEmbedUnimplementedDriversvcServer()
}

// UnimplementedDriversvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriversvcServer struct{}

func (UnimplementedDriversvcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDriversvcServer) CreateDriver(context.Context, *CreateDriverRequest) (*CreateDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDriver not implemented")
}
func (UnimplementedDriversvcServer) UpdateDriver(context.Context, *UpdateDriverRequest) (*UpdateDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDriver not implemented")
}
func (UnimplementedDriversvcServer) DeleteDriver(context.Context, *DeleteDriverRequest) (*DeleteDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDriver not implemented")
}
func (UnimplementedDriversvcServer) GetDriver(context.Context, *GetDriverRequest) (*GetDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriver not implemented")
}
func (UnimplementedDriversvcServer) ListDrivers(context.Context, *ListDriversRequest) (*ListDriversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrivers not implemented")
}
func (UnimplementedDriversvcServer) mustEmbedUnimplementedDriversvcServer() {}
func (UnimplementedDriversvcServer) testEmbeddedByValue()                   {}

// UnsafeDriversvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriversvcServer will
// result in compilation errors.
type UnsafeDriversvcServer interface {
	mustEmbedUnimplementedDriversvcServer()
}

func RegisterDriversvcServer(s grpc.ServiceRegistrar, srv DriversvcServer) {
	// If the following call panics, it indicates UnimplementedDriversvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Driversvc_ServiceDesc, srv)
}

func _Driversvc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriversvcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driversvc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriversvcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driversvc_CreateDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriversvcServer).CreateDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driversvc_CreateDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriversvcServer).CreateDriver(ctx, req.(*CreateDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driversvc_UpdateDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriversvcServer).UpdateDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driversvc_UpdateDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriversvcServer).UpdateDriver(ctx, req.(*UpdateDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driversvc_DeleteDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriversvcServer).DeleteDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driversvc_DeleteDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriversvcServer).DeleteDriver(ctx, req.(*DeleteDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driversvc_GetDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriversvcServer).GetDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driversvc_GetDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriversvcServer).GetDriver(ctx, req.(*GetDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driversvc_ListDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriversvcServer).ListDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driversvc_ListDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriversvcServer).ListDrivers(ctx, req.(*ListDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Driversvc_ServiceDesc is the grpc.ServiceDesc for Driversvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driversvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driversvc.Driversvc",
	HandlerType: (*DriversvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Driversvc_Ping_Handler,
		},
		{
			MethodName: "CreateDriver",
			Handler:    _Driversvc_CreateDriver_Handler,
		},
		{
			MethodName: "UpdateDriver",
			Handler:    _Driversvc_UpdateDriver_Handler,
		},
		{
			MethodName: "DeleteDriver",
			Handler:    _Driversvc_DeleteDriver_Handler,
		},
		{
			MethodName: "GetDriver",
			Handler:    _Driversvc_GetDriver_Handler,
		},
		{
			MethodName: "ListDrivers",
			Handler:    _Driversvc_ListDrivers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/driversvc/proto/driversvc.proto",
}
