// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: paysvc.proto

package pay

import (
	"context"

	__proto "XiaoLong-Ridy/rpc/paysvc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePaymentRequest      = __proto.CreatePaymentRequest
	CreatePaymentResponse     = __proto.CreatePaymentResponse
	GetPaymentRequest         = __proto.GetPaymentRequest
	GetPaymentResponse        = __proto.GetPaymentResponse
	GetSettlementRequest      = __proto.GetSettlementRequest
	GetSettlementResponse     = __proto.GetSettlementResponse
	ListSettlementsRequest    = __proto.ListSettlementsRequest
	ListSettlementsResponse   = __proto.ListSettlementsResponse
	NotifyPaymentRequest      = __proto.NotifyPaymentRequest
	NotifyPaymentResponse     = __proto.NotifyPaymentResponse
	RefundPaymentRequest      = __proto.RefundPaymentRequest
	RefundPaymentResponse     = __proto.RefundPaymentResponse
	SettleOrderRequest        = __proto.SettleOrderRequest
	SettleOrderResponse       = __proto.SettleOrderResponse
	SettlementBill            = __proto.SettlementBill

	Pay interface {
		// 支付预下单：创建支付单并调第三方下单（本期为 mock）。
		CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
		// 支付回调：处理第三方支付结果通知（验签 + 更新状态）。
		NotifyPayment(ctx context.Context, in *NotifyPaymentRequest, opts ...grpc.CallOption) (*NotifyPaymentResponse, error)
		// 支付查询：按支付单号或订单ID查询支付状态。
		GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error)
		// 退款：退款并回写支付单。
		RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...grpc.CallOption) (*RefundPaymentResponse, error)
		// 司机结算：计算平台抽成与司机实收。
		SettleOrder(ctx context.Context, in *SettleOrderRequest, opts ...grpc.CallOption) (*SettleOrderResponse, error)
		// 结算查询：按订单ID查询司机结算单，供管理后台展示。
		GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*GetSettlementResponse, error)
		// 结算列表：按司机/状态/时间范围分页查询结算单。
		ListSettlements(ctx context.Context, in *ListSettlementsRequest, opts ...grpc.CallOption) (*ListSettlementsResponse, error)
	}

	defaultPay struct {
		cli zrpc.Client
	}
)

func NewPay(cli zrpc.Client) Pay {
	return &defaultPay{
		cli: cli,
	}
}

// 支付预下单：创建支付单并调第三方下单（本期为 mock）。
func (m *defaultPay) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	client := __proto.NewPayClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

// 支付回调：处理第三方支付结果通知（验签 + 更新状态）。
func (m *defaultPay) NotifyPayment(ctx context.Context, in *NotifyPaymentRequest, opts ...grpc.CallOption) (*NotifyPaymentResponse, error) {
	client := __proto.NewPayClient(m.cli.Conn())
	return client.NotifyPayment(ctx, in, opts...)
}

// 支付查询：按支付单号或订单ID查询支付状态。
func (m *defaultPay) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error) {
	client := __proto.NewPayClient(m.cli.Conn())
	return client.GetPayment(ctx, in, opts...)
}

// 退款：退款并回写支付单。
func (m *defaultPay) RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...grpc.CallOption) (*RefundPaymentResponse, error) {
	client := __proto.NewPayClient(m.cli.Conn())
	return client.RefundPayment(ctx, in, opts...)
}

// 司机结算：计算平台抽成与司机实收。
func (m *defaultPay) SettleOrder(ctx context.Context, in *SettleOrderRequest, opts ...grpc.CallOption) (*SettleOrderResponse, error) {
	client := __proto.NewPayClient(m.cli.Conn())
	return client.SettleOrder(ctx, in, opts...)
}

// 结算查询：按订单ID查询司机结算单，供管理后台展示。
func (m *defaultPay) GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*GetSettlementResponse, error) {
	client := __proto.NewPayClient(m.cli.Conn())
	return client.GetSettlement(ctx, in, opts...)
}

// 结算列表：按司机/状态/时间范围分页查询结算单。
func (m *defaultPay) ListSettlements(ctx context.Context, in *ListSettlementsRequest, opts ...grpc.CallOption) (*ListSettlementsResponse, error) {
	client := __proto.NewPayClient(m.cli.Conn())
	return client.ListSettlements(ctx, in, opts...)
}
