// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ordersvc.proto

package order

import (
	"context"

	"XiaoLong-Ridy/rpc/ordersvc/proto/XiaoLong-Ridy/rpc/ordersvc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderRequest  = pb.CreateOrderRequest
	CreateOrderResponse = pb.CreateOrderResponse

	Order interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}
